# Get Bioavailable Iron from USDA

In [252]:
# Parameters
SAVE_DFS = True

In [253]:
import ast
import os
import pandas as pd
import requests

from dotenv import load_dotenv
from IPython.display import Image
from pathlib import Path
from rapidfuzz import process, fuzz
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [254]:
# Load splits from CSVs
df_train = pd.read_csv('../data/train/df_train.csv')
df_val = pd.read_csv('../data/val/df_val.csv')
df_test = pd.read_csv('../data/test/df_test.csv')

df_train.head(2)

,image_url,camera_or_phone_prob,food_prob,dish_name,food_type,ingredients,portion_size,nutritional_profile,cooking_method,sub_dt,image_name
0,https://file.b18a.io/7832973280900104501_54585...,0.8,0.90,oysters,homemade food,['oysters'],{'oysters': '500g'},"{'fat_g': 5.0, 'protein_g': 20.0, 'calories_kc...",raw,20250710,7832973280900104501_545859_.jpeg
1,https://file.b18a.io/7835136777400102715_70587...,0.7,0.95,grilled steak,restaurant food,"['steak', 'broccoli', 'potato', 'tomato', 'sau...","{'steak': '250g', 'broccoli': '50g', 'potato':...","{'fat_g': 30.0, 'protein_g': 50.0, 'calories_k...",grilling,20250702,7835136777400102715_705873_.jpeg

In [255]:
# Combine dfs
df_all = pd.concat([df_train, df_val, df_test])
df_all = df_all.reset_index()

df_all.shape

(5000, 12)

In [256]:
df_all['dish_name']

0                              oysters
1                        grilled steak
2              sweet and sour potatoes
3                              hot pot
4                   stir-fried noodles
                     ...
4995                       noodle soup
4996              braised chicken feet
4997                           hot pot
4998    vegetable and chicken sandwich
4999                mixed asian dishes
Name: dish_name, Length: 5000, dtype: object

In [257]:
df_all['portion_size'][0]

"{'oysters': '500g'}"

In [258]:
df_all['portion_size'] = df_all['portion_size'].apply(ast.literal_eval)

df_all['portion_size'][0]

{'oysters': '500g'}

In [259]:
# Get all ingredients
ingredients = set()
for row in df_all.itertuples():
    keys = row.portion_size.keys()
    ingredients.update(row.portion_size.keys())
print(f'{len(ingredients)=}')
ingredients

len(ingredients)=798

{'abalone',
 'almonds',
 'anchovies',
 'apple',
 'apple chips',
 'apples',
 'apricot',
 'apricots',
 'asparagus',
 'assorted desserts',
 'avocado',
 'baby corn',
 'bacon',
 'bagel',
 'baked beans',
 'baked goods',
 'baked potato',
 'baklava',
 'bamboo shoots',
 'banana',
 'bananas',
 'bao dough',
 'bar',
 'base',
 'basil',
 'batter',
 'bbq ribs',
 'bean sprouts',
 'beans',
 'beef',
 'beef liver',
 'beef patty',
 'beef ribs',
 'beef snack',
 'beef stew',
 'beef tripe',
 'beer',
 'beet',
 'beetroot',
 'beets',
 'bell pepper',
 'bell peppers',
 'berries',
 'beverage',
 'beverages',
 'bird',
 'birds',
 'biscuit',
 'biscuits',
 'bitter melon',
 'black beans',
 'black fungus',
 'black jelly',
 'black olive tapenade',
 'black pudding',
 'black rice',
 'black sapote',
 'blackberries',
 'blueberries',
 'boiled egg',
 'boiled eggs',
 'bok choy',
 'borscht',
 'bounty bar',
 'bread',
 'bread roll',
 'bread rolls',
 'breading',
 'brisket',
 'broad beans',
 'broccoli',
 'broth',
 'buckwheat',
 'bulgur',
 'bun',
 'buns',
 'burger',
 'burger patty',
 'butter',
 'cabbage',
 'cabbage rolls',
 'cake',
 'cakes',
 'calamari',
 'can',
 'candy',
 'canned beverage',
 'cantaloupe',
 'caramel sauce',
 'carrot',
 'carrots',
 'cashew nuts',
 'cashews',
 'cassava',
 'casserole',
 'cauliflower',
 'caviar',
 'celery',
 'century eggs',
 'cereal',
 'char siu',
 'cheddar cheese',
 'cheese',
 'cheese filling',
 'cheese sauce',
 'cheese sticks',
 'cheesecake',
 'cherries',
 'cherry',
 'cherry tomatoes',
 'chestnuts',
 'chicken',
 'chicken breast',
 'chicken drumstick',
 'chicken drumsticks',
 'chicken feet',
 'chicken leg',
 'chicken mcnuggets',
 'chicken nuggets',
 'chicken patty',
 'chicken skewers',
 'chicken strips',
 'chicken tenders',
 'chicken wing',
 'chicken wings',
 'chickpeas',
 'chili',
 'chili peppers',
 'chips',
 'chocolate',
 'chocolate bar',
 'chocolate cake',
 'chocolate ice cream',
 'chocolate roll cake',
 'chocolate sauce',
 'chocolate spread',
 'chocolate tart',
 'chutney',
 'cilantro',
 'clam',
 'clams',
 'coconut',
 'coconut drink',
 'coconut flour',
 'coconut jelly',
 'coconut milk',
 'coconut milk dessert',
 'coconut water',
 'coffee',
 'coffee beans',
 'coffee concentrate',
 'coffee sachet',
 'coleslaw',
 'condiment',
 'condiment1',
 'condiment2',
 'condiment3',
 'condiments',
 'cone',
 'cooked eggs',
 'cookie',
 'cookie cup',
 'cookie rolls',
 'cookies',
 'corn',
 'cottage cheese',
 'couscous',
 'crab',
 'crabs',
 'crackers',
 'cracklings',
 'cranberries',
 'crawfish',
 'crayfish',
 'cream',
 'cream base',
 'cream puff',
 'cream sauce',
 'cream tart',
 'creamy dip',
 'creamy sauce',
 'crepes',
 'crisps',
 'crispy cups',
 'crispy topping',
 'crispy toppings',
 'croissant',
 'croquettes',
 'croutons',
 'crust',
 'crème brûlée',
 'cucumber',
 'cucumbers',
 'cup',
 'cupcake',
 'cured meat',
 'curry',
 'curry bread',
 'custard',
 'cutlet',
 'daikon',
 'dairy',
 'dairy drink',
 'date',
 'dates',
 'dessert',
 'dessert cup',
 'desserts',
 'dip',
 'dipping sauce',
 'donut',
 'doritos',
 'dough',
 'dough balls',
 'dough sticks',
 'dragon fruit',
 'dressing',
 'dried chili',
 'dried chilies',
 'dried cranberries',
 'dried fruit',
 'dried fruits',
 'dried mushrooms',
 'dried plums',
 'dried tomatoes',
 'drink',
 'drink1',
 'drink2',
 'drink3',
 'drink4',
 'drinks',
 'duck',
 'dumpling',
 'dumpling wrapper',
 'dumplings',
 'durian',
 'edamame',
 'eel',
 'efo riro',
 'egg',
 'egg dish',
 'egg tart',
 'eggplant',
 'eggs',
 'energy drink',
 'espresso',
 'falafel',
 'fanta',
 'filet mignon',
 'filling',
 'fish',
 'fish cakes',
 'fish roe',
 'fish skin',
 'flan',
 'flatbread',
 'flour',
 'french fries',
 'french toast',
 'fried balls',
 'fried batter',
 'fried bread',
 'fried cakes',
 'fried chicken',
 'fried dish',
 'fried dough',
 'fried dough balls',
 'fried dough stick',
 'fried dough sticks',
 'fried dumplings',
 'fried egg',
 'fried eggplant',
 'fried elements',
 'fried fish',
 'fried item',
 'fried items',
 'fried meat',
 'fried nuggets',
 'fried onions',
 'fried pork',
 'fried pork cutlet',
 'fried potatoes',
 'fried rice',
 'fried rolls',
 'fried shrimp',
 'fried sides',
 'fried snack',
 'fried snacks',
 'fried tofu',
 'fried toppings',
 'fried vegetables',
 'fries',
 'fritter',
 'fritters',
 'frog legs',
 'frosting',
 'frozen fruit pop',
 'fruit',
 'fruit filling',
 'fruit mix',
 'fruit puree',
 'fruit smoothie',
 'fruit1',
 'fruit2',
 'fruits',
 'fudge',
 'fufu',
 'garlic',
 'garnish',
 'garnishes',
 'gelatin',
 'gelato',
 'ginger',
 'glaze',
 'glutinous rice',
 'glutinous rice balls',
 'gnocchi',
 'goat milk powder',
 'goji berries',
 'grains',
 'granola',
 'grape leaves',
 'grapefruit',
 'grapes',
 'gravy',
 'green apples',
 'green beans',
 'green bell pepper',
 'green cake',
 'green chili',
 'green chilies',
 'green grapes',
 'green onion',
 'green onions',
 'green peas',
 'green pepper',
 'green peppers',
 'green tea',
 'green tea ice cream',
 'green vegetables',
 'greens',
 'grilled chicken',
 'grilled eel',
 'grilled fish',
 'grilled lemon',
 'grilled meat',
 'grilled squash',
 'ground beef',
 'ground meat',
 'ground pork',
 'gummy bears',
 'ham',
 'hamburger patty',
 'hamburger steak',
 'hash browns',
 'hawthorn',
 'herbs',
 'honey',
 'honeycomb',
 'hot dog',
 'hot dogs',
 'hot pot',
 'hot pot ingredients',
 'hummus',
 'ice',
 'ice cream',
 'ice cream bar',
 'insects',
 'jackfruit',
 'jelly',
 'juice',
 'jujube',
 'jujubes',
 'kale',
 'kataifi',
 'kebab',
 'kebabs',
 'kefir',
 'ketchup',
 'kibble',
 'kimchi',
 'kiwi',
 'kiwifruit',
 'kozinaki',
 'lamb',
 'lamb chops',
 'lasagna',
 'leaf',
 'leafy greens',
 'leaves',
 'leeks',
 'legumes',
 'lemon',
 'lemons',
 'lentil curry',
 'lentils',
 'lettuce',
 'lime',
 'liver',
 'lobster',
 'lollipops',
 'longan',
 'loquat',
 'lotus root',
 'lotus root slices',
 'lychee',
 'macaron',
 'mackerel',
 'madeleines',
 'main dish',
 'main ingredient',
 'mango',
 'mangosteen',
 'marshmallows',
 'mashed potatoes',
 'matcha',
 'matcha cream',
 'mayonnaise',
 'mcspicy wings',
 'meat',
 'meat dish',
 'meat filling',
 'meat patty',
 'meat sauce',
 'meat skewers',
 'meat topping',
 'meatball',
 'meatballs',
 'meatloaf',
 'melon',
 'melon seeds',
 'meringue',
 'milk',
 'milk tea',
 'minced meat',
 'mini cakes',
 'mint',
 'mint candy',
 'mint ice cream',
 'mix',
 'mixed dish',
 'mixed fruits',
 'mixed vegetables',
 'mochi',
 'momos',
 'morning glory',
 'mozzarella',
 'mozzarella sticks',
 'muffin',
 'mulberries',
 'mung beans',
 'mushrooms',
 'mussels',
 'mustard',
 'naan',
 'nabati',
 'nachos',
 'nectarine',
 'nextar',
 'noodle dish',
 'noodle soup',
 'noodles',
 'nori',
 'nougat',
 'nuts',
 'oat milk',
 'oat snack',
 'oatmeal',
 'oats',
 'octopus',
 'oil',
 'okra',
 'olive oil',
 'olives',
 'omelet',
 'onion',
 'onion rings',
 'onions',
 'orange',
 'orange juice',
 'orange pepper',
 'oranges',
 'oreo',
 'organ meat',
 'other dishes',
 'other ingredients',
 'other vegetables',
 'oysters',
 'pakoras',
 'pancake',
 'pancakes',
 'panna cotta',
 'papaya',
 'parsley',
 'passion fruit',
 'pasta',
 'pasta shells',
 'pastries',
 'pastry',
 'pastry crust',
 'pastry1',
 'pastry2',
 'pastry3',
 'pastry4',
 'patties',
 'patty',
 'peach',
 'peach slices',
 'peaches',
 'peanut butter',
 'peanut sauce',
 'peanuts',
 'pear',
 'pears',
 'peas',
 'pecans',
 'pepper',
 'peppers',
 'pesto',
 'pickled fish',
 'pickled radish',
 'pickled vegetables',
 'pickles',
 'pie',
 'pine nuts',
 'pineapple',
 'pistachio tart',
 'pistachios',
 'pizza',
 'pizza slice',
 'plantain',
 'plantain chips',
 'plantains',
 'plum',
 'plums',
 'poached egg',
 'pomegranate',
 'pomelo',
 'popcorn',
 'popsicle',
 'pork',
 'pork belly',
 'pork bits',
 'pork brain',
 'pork bun',
 'pork floss',
 'pork head',
 'pork hock',
 'pork hocks',
 'pork knuckle',
 'pork ribs',
 'pork trotters',
 'porridge',
 'potato',
 'potato chips',
 'potato sticks',
 'potato wedge',
 'potatoes',
 'pounded yam',
 'powder',
 'preserved egg',
 'processed meat',
 'protein',
 'protein drink',
 'protein source',
 'pudding',
 'puff pastry',
 'pumpkin',
 'pumpkin seeds',
 'puri',
 'purple yam',
 'quinoa',
 'radish',
 'radishes',
 'raisins',
 'rambutan',
 'rasgulla',
 'raspberries',
 'raspberry',
 'raw vegetables',
 'red apples',
 'red bean paste',
 'red beans',
 'red bell pepper',
 'red chili',
 'red chilies',
 'red currants',
 'red grapes',
 'red pepper',
 'red peppers',
 'ribs',
 'rice',
 'rice cake',
 'rice cakes',
 'rice flour',
 'rice noodles',
 'rice paper',
 'rice porridge',
 'rice rolls',
 'ricotta',
 'roast meat',
 'roasted chicken',
 'roasted duck',
 'roasted meat',
 'roasted potatoes',
 'roll',
 'rolled meat',
 'rolls',
 'root vegetables',
 'roti',
 'rye bread',
 'sago',
 'salad',
 'salad greens',
 'salmon',
 'salmon sushi',
 'salsa',
 'sambal',
 'samosa',
 'samosas',
 'sandwich',
 'sashimi',
 'sauce',
 'sauces',
 'sauerkraut',
 'sausage',
 'sausages',
 'savory pancake',
 'savory snack',
 'scallions',
 'scallop',
 'scallops',
 'scrambled eggs',
 'sea urchin',
 'seafood',
 'seafood skewers',
 'seafood stew',
 'seafood topping',
 'seasoning',
 'seaweed',
 'seeds',
 'semolina',
 'sesame',
 'sesame bread',
 'sesame seeds',
 'shaved ice',
 'shellfish',
 'short ribs',
 'shortbread',
 'shredded crab',
 'shredded meat',
 'shredded vegetables',
 'shrimp',
 'shrimp dish',
 'shrimp dumpling',
 'shrimp porridge',
 'side',
 'side dish',
 'side dishes',
 'side item',
 'side salad',
 'side vegetables',
 'sides',
 'skewered meat',
 'skewers',
 'skittles',
 'sliced meat',
 'small fish',
 'smoked salmon',
 'smoothie',
 'snack',
 'snack balls',
 'snack mix',
 'snack sticks',
 'snack1',
 'snack2',
 'snack3',
 'snacks',
 'snails',
 'snap peas',
 'soba noodles',
 'soda',
 'soup',
 'soup base',
 'sour cream',
 'soy milk',
 'soy sauce',
 'soybeans',
 'soymilk',
 'spaghetti',
 'spice mix',
 'spices',
 'spinach',
 'split peas',
 'sponge cake',
 'spread',
 'spring roll',
 'spring rolls',
 'sprouts',
 'squash',
 'squid',
 'starch',
 'starchy side',
 'starfruit',
 'steak',
 'steamed buns',
 'steamed vegetables',
 'stew',
 'sticks',
 'sticky rice',
 'stir-fried chicken',
 'stir-fried vegetables',
 'stir-fried vegetables and meat',
 'stir-fry',
 'strawberries',
 'strawberry',
 'stuffing',
 'sugar',
 'sugar syrup',
 'sun-dried tomatoes',
 'sunflower seeds',
 'sushi',
 'sushi rice',
 'sushi roll',
 'sweet bread',
 'sweet dish',
 'sweet paste',
 'sweet potato',
 'sweet potatoes',
 'sweet soup',
 'sweet toppings',
 'sweet treat',
 'sweetener',
 'swiss roll',
 'syrup',
 'tacos',
 'tangerine',
 'tapioca',
 'tapioca balls',
 'tapioca pearls',
 'taro cake',
 'tart',
 'tart base',
 'tart crust',
 'tea',
 'tea bag',
 'tea leaves',
 'tempeh',
 'tempura',
 'toast',
 'tofu',
 'tomato',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'topping',
 'toppings',
 'tortilla',
 'tortilla chips',
 'tortillas',
 'tuna',
 'tuna sushi',
 'turkey',
 'twix',
 'udon',
 'vegetable bites',
 'vegetable curry',
 'vegetable dish',
 'vegetable mixture',
 'vegetable pancake',
 'vegetable sauce',
 'vegetable skewers',
 'vegetable stew',
 'vegetable stir-fry',
 'vegetables',
 'wafer',
 'wafer cone',
 'wafer sticks',
 'waffle',
 'waffles',
 'walnut',
 'walnut milk',
 'wasabi',
 'water',
 'watermelon',
 'watermelon candy',
 'whipped cream',
 'whole grain bread',
 'wontons',
 'wood ear mushrooms',
 'wrap',
 'wrapper',
 'yakult',
 'yams',
 'yeast',
 'yellow cherries',
 'yogurt',
 'zucchini'}

In [260]:
nutrient_names = ['Iron, Fe', 'Calcium, Ca', 'Vitamin C, total ascorbic acid']

ingredients_df = {'ingredients': list(ingredients)}
ingredients_df = pd.DataFrame(ingredients_df)
for name in nutrient_names:
    ingredients_df[name] = ''
ingredients_df

         ingredients Iron, Fe Calcium, Ca Vitamin C, total ascorbic acid
0       dough sticks
1     fried potatoes
2              gravy
3             crisps
4         black rice
..               ...      ...         ...                            ...
793         scallops
794  shrimp porridge
795        buckwheat
796           gelato
797         tomatoes

[798 rows x 4 columns]

In [261]:
csv_file = '../data/ingredients.csv'

if SAVE_DFS:
    # Save to CSV
    ingredients_df.to_csv(csv_file, index=False)

# Load data from previously saved CSV
ingredients_df = pd.read_csv(csv_file)
ingredients_df

         ingredients  Iron, Fe  Calcium, Ca  Vitamin C, total ascorbic acid
0       dough sticks       NaN          NaN                             NaN
1     fried potatoes       NaN          NaN                             NaN
2              gravy       NaN          NaN                             NaN
3             crisps       NaN          NaN                             NaN
4         black rice       NaN          NaN                             NaN
..               ...       ...          ...                             ...
793         scallops       NaN          NaN                             NaN
794  shrimp porridge       NaN          NaN                             NaN
795        buckwheat       NaN          NaN                             NaN
796           gelato       NaN          NaN                             NaN
797         tomatoes       NaN          NaN                             NaN

[798 rows x 4 columns]

## USDA FoodData Central API

In [262]:
# Load and get api key from .env
load_dotenv()
api_key = os.getenv("API_KEY")

FOODS_SEARCH_URL = 'https://api.nal.usda.gov/fdc/v1/foods/search'

In [263]:
# Search for food
ingredient = 'porridge'
food_query = ingredient
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
data = r.json()
data_df = pd.DataFrame.from_dict(data['foods'])
if len(data_df) == 0:  # Data not found
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
data_df

,fdcId,description,dataType,publishedDate,tags,allHighlightFields,score,microbes,foodNutrients,finalFoodInputFoods,...,packageWeight,servingSizeUnit,servingSize,householdServingFullText,shortDescription,tradeChannels,commonNames,additionalDescriptions,foodCode,foodCategoryId
0,2687788,Potential of moringa leaf and baobab fruit foo...,Experimental,2024-04-18,"[Processing, Post-Harvest, USDA Research]",,303.968050,[],[],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2417422,"MULTIGRAIN PORRIDGE SLICED BREAD, TARTINE MULT...",Branded,2022-12-22,NaN,,230.002460,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2 oz/500 g,g,50.0,1 slice,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
2,2089884,ARTIFICIAL CHICKEN PORRIDGE,Branded,2021-10-28,NaN,<b>Ingredients</b>: <em>PORRIDGE</em> (52%): R...,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,4.2 oz/120 g,g,120.0,1 BOWL,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
3,2168938,ORGANIC PORRIDGE OATS,Branded,2021-10-28,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,35 oz/2.19 LB/992 g,g,40.0,1/2 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
4,1002697,PUMPKIN PORRIDGE WITH HONEY,Branded,2020-06-26,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
5,552097,RICE PORRIDGE WITH ABALONE,Branded,2019-04-01,NaN,,202.842590,[],"[{'nutrientId': 1004, 'nutrientName': 'Total l...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
6,552435,RICE PORRIDGE WITH TUNA,Branded,2019-04-01,NaN,,202.842590,[],"[{'nutrientId': 1087, 'nutrientName': 'Calcium...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
7,560546,RICE PORRIDGE WITH VEGETABLE,Branded,2019-04-01,NaN,,202.842590,[],"[{'nutrientId': 1004, 'nutrientName': 'Total l...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
8,2089623,SUPER SMOOTH PORRIDGE,Branded,2021-10-28,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,100.0,100 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
9,2432400,"TEFF PORRIDGE, IVORY",Branded,2022-12-22,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,5 oz/142 g,g,50.0,0.25 cup,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
10,2642126,"CORNMEAL INSTANT PORRIDGE, CORNMEAL",Branded,2023-09-14,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2.1 oz/60 g,GRM,60.0,1 container,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
11,2132017,"CORNMEAL INSTANT PORRIDGE, PEANUT",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,60 g/2.10 oz,g,60.0,60 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
12,2055230,"OATMEAL INSTANT PORRIDGE, BANANA",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,74 g/2.6 oz,g,74.0,74 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
13,2035067,"OTTOGI, VEGETABLE RICE PORRIDGE",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,34.0,2.5 Tbsp,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
14,2111605,"PAMANA, CHICKEN RICE PORRIDGE",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,1.7 oz/48 g,g,48.0,1 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
15,2317368,Pams Creamy Porridge 850g,Branded,2022-05-23,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,850g,g,45.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
16,510622,CHAO CA FISH INSTANT PORRIDGE,Branded,2019-04-01,NaN,<b>Ingredients</b>: <em>PORRIDGE</em> (51.2%):...,111.640500,[],"[{'nutrientId': 1079, 'nutrientName': 'Fiber, ...",[],...,NaN,g,120.0,1 BOWL,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
17,2132824,"CINNAMON CORNMEAL INSTANT PORRIDGE, CINNAMON",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,60 g/2.10 oz,g,60.0,60 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
18,2114466,"OAT MEAL INSTANT PORRIDGE, ALMOND",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,74 g/2.6 oz,g,74.0,74 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
19,2035053,"OTTOGI, BLACK SESAME RICE PORRIDGE",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,32.0,2.5 Tbsp,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
20,2037377,"OTTOGI, SWEET RED BEAN PORRIDGE",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,285.0,1 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
21,1002425,SWEET RED BEAN AND CHESTNUT PORRIDGE,Branded,2020-06-26,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
22,2642127,"GREEN BANANA INSTANT PORRIDGE, GREEN BANANA",Branded,2023-09-14,NaN,,75.443140,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,1.9 oz/55 g,GRM,55.0,1 container,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
23,2108195,"PAMANA, MUNG BEAN PORRIDGE WITH COCONUT MILK",Branded,2021-10-28,NaN,,75.443140,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2.65 oz/75 g,g,75.0,1 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
24,2288195,"PAMANA, GINATAANG MAIS, CORN PORRIDGE WITH COC...",Branded,2022-05-23,NaN,,43.901890,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2.65 oz,g,75.0,1 cup,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
25,2182865,Pure Delish Bircher Porridge Creamy Chia 400g,Branded,2021-10-28,NaN,,43.901890,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,400g,g,40.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
26,2182866,Pure Delish Bircher Porridge Wild Blueberry 400g,Branded,2021-10-28,NaN,,43.901890,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,400g,g,40.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
27,2708418,Congee,Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gruel,26.327248,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Beverages, water, tap, d...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel,56205101.0,3304384.0
28,2708984,"Congee, with egg",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gruel,26.327248,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Eggs, Grade A, Large, eg...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel,58157330.0,3305516.0
29,2015623,"OLD WESSEX LTD., SCOTTISH-STYLE PORRIDGE OATS ...",Branded,2021-10-28,NaN,<b>Ingredients</b>: 100% NATURAL SCOTTISH-STYL...,25.215652,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,18.5 oz/524 g,g,40.0,0.5 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
30,2708981,"Congee, with meat, poultry, and/or seafood",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: with egg;rice <em>porridge</e...,24.450163,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Salt, table', 'gramWeigh...",...,NaN,NaN,NaN,NaN,NaN,NaN,,with egg;rice porridge or gruel,58157300.0,3305510.0
31,2708982,"Congee, with meat, poultry, and/or seafood, an...",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gru...,24.450163,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Congee, with meat, poult...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel;with egg,58157310.0,3305512.0
32,2708983,"Congee, with vegetables",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gru...,24.450163,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Rice, white, long-grain,...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel;with beans,58157320.0,3305514.0
33,2182880,Pure Delish Bircher Porridge Dark Chocolate & ...,Branded,2021-10-28,NaN,,16.172852,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,400g,g,40.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
34,2440243,JUMBO OATS,Branded,2022-12-22,NaN,<b>Ingredients</b>: PURE SCOTTISH <em>PORRIDGE...,-397.155670,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,750 g,g,40.0,1 cup,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN

In [264]:
# Fuzzy string matching
food_names = data_df['description']
best_match = process.extractOne(ingredient, food_names, scorer=fuzz.ratio)

print(f"Ingredient: {ingredient}")
print(f"Best match: {best_match[0]} with a score of {best_match[1]}")
data_df = data_df.loc[data_df['description']==best_match[0]].head(1).reset_index()
data_df

Ingredient: porridge
Best match: Congee with a score of 42.85714285714286

,index,fdcId,description,dataType,publishedDate,tags,allHighlightFields,score,microbes,foodNutrients,...,packageWeight,servingSizeUnit,servingSize,householdServingFullText,shortDescription,tradeChannels,commonNames,additionalDescriptions,foodCode,foodCategoryId
0,27,2708418,Congee,Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gruel,26.327248,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel,56205101.0,3304384.0

In [265]:
# Get food nutrients
nutrients = pd.DataFrame(data_df.iloc[0]['foodNutrients'])
nutrients = nutrients.loc[nutrients['nutrientName'].isin(nutrient_names)][['nutrientName', 'value']]
nutrients

                      nutrientName  value
10                     Calcium, Ca   5.00
11                        Iron, Fe   0.36
28  Vitamin C, total ascorbic acid   0.00

In [266]:
def get_nutrients(data_df, ingredients_df, nutrient_names):
    if len(data_df) > 0:  # Food found

        # Fuzzy string matching
        food_names = data_df['description']
        best_match = process.extractOne(ingredient, food_names, scorer=fuzz.ratio)
        data_df = data_df.loc[data_df['description']==best_match[0]].head(1).reset_index()
        nutrients = data_df.iloc[0]
        if len(nutrients) > 0:  # Nutrients found
            food_id = nutrients['fdcId']
            food_name = nutrients['description']  # Skip if foodNutrients missing
            nutrients = pd.DataFrame(nutrients['foodNutrients'])
            if len(nutrients) > 0:
                nutrients = nutrients.loc[nutrients['nutrientName'].isin(nutrient_names)][['nutrientName', 'value']]
                for row in nutrients.itertuples():
                    ingredients_df.loc[ingredients_df['ingredients']==ingredient, row.nutrientName] = row.value
                ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'found'] = True
                ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'food_id'] = food_id
                ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'food_name'] = food_name
        
        # nutrients = pd.DataFrame()
        # i = 0
        # while len(nutrients) == 0 and i < len(data_df):  # Look for entry with nutrients
        #     # nutrients = pd.DataFrame(data_df.iloc[i]['foodNutrients'])
        #     nutrients = data_df.iloc[i]
        #     i += 1
        #     if len(nutrients) > 0:  # Nutrients found
        #         food_id = nutrients['fdcId']
        #         food_name = nutrients['description']  # Skip if foodNutrients missing
        #         nutrients = pd.DataFrame(nutrients['foodNutrients'])
        #         if len(nutrients) == 0:
        #             continue
        #         nutrients = nutrients.loc[nutrients['nutrientName'].isin(nutrient_names)][['nutrientName', 'value']]
        #         if len(nutrients) == 0:  # Skip if no desired nutrients
        #             continue
        #         for row in nutrients.itertuples():
        #             ingredients_df.loc[ingredients_df['ingredients']==ingredient, row.nutrientName] = row.value
        #         ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'found'] = True
        #         ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'food_id'] = food_id
        #         ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'food_name'] = food_name
        #         break

    return ingredients_df

In [267]:
# Init food info
ingredients_df['found'] = False
ingredients_df['food_id'] = ''
ingredients_df['food_name'] = ''

In [ ]:
# Fill CSV with nutrient data for ingredients
csv_file = '../data/ingredients_auto.csv'

for ingredient in tqdm(ingredients):
    # Search for food
    food_query = ingredient
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
    # Get food nutrients
    ingredients_df = get_nutrients(data_df, ingredients_df, nutrient_names)

    # Check if food not found earlier, broaden food search
    if ingredients_df.loc[ingredients_df['ingredients']==ingredient]['found'].item() == False:
        r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
        data = r.json()
        data_df = pd.DataFrame.from_dict(data['foods'])
        # Get food nutrients
        ingredients_df = get_nutrients(data_df, ingredients_df, nutrient_names)

    if SAVE_DFS:
        # Save to CSV
        ingredients_df.to_csv(csv_file, index=False)

# Load data from previously saved CSV
ingredients_df = pd.read_csv(csv_file)
ingredients_df

  1%|          | 9/798 [00:05<06:54,  1.90it/s]

In [ ]:
ingredients_df.loc[ingredients_df['found']==False]

,ingredients,"Iron, Fe","Calcium, Ca","Vitamin C, total ascorbic acid",found,food_id,food_name
26,condiment2,NaN,NaN,NaN,False,NaN,NaN
76,kozinaki,NaN,NaN,NaN,False,NaN,NaN
90,drink3,NaN,NaN,NaN,False,NaN,NaN
93,fruit2,NaN,NaN,NaN,False,NaN,NaN
130,drink1,NaN,NaN,NaN,False,NaN,NaN
137,drink2,NaN,NaN,NaN,False,NaN,NaN
215,drink4,NaN,NaN,NaN,False,NaN,NaN
233,snack1,NaN,NaN,NaN,False,NaN,NaN
315,nextar,NaN,NaN,NaN,False,NaN,NaN
341,pastry4,NaN,NaN,NaN,False,NaN,NaN
456,rasgulla,NaN,NaN,NaN,False,NaN,NaN
472,efo riro,NaN,NaN,NaN,False,NaN,NaN
511,condiment1,NaN,NaN,NaN,False,NaN,NaN
595,snack3,NaN,NaN,NaN,False,NaN,NaN
598,condiment3,NaN,NaN,NaN,False,NaN,NaN
641,snack2,NaN,NaN,NaN,False,NaN,NaN
694,pastry1,NaN,NaN,NaN,False,NaN,NaN
723,pastry2,NaN,NaN,NaN,False,NaN,NaN
739,pastry3,NaN,NaN,NaN,False,NaN,NaN

In [ ]:
# Search for food
ingredient = 'condiment'
food_query = ingredient
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
data = r.json()
data_df = pd.DataFrame.from_dict(data['foods'])
if len(data_df) == 0:  # Data not found
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
data_df

,fdcId,description,dataType,gtinUpc,publishedDate,brandOwner,brandName,ingredients,marketCountry,foodCategory,...,foodAttributeTypes,foodVersionIds,commonNames,additionalDescriptions,ndbNumber,shortDescription,subbrandName,preparationStateCode,footnote,gpcClassCode
0,2028508,CONDIMENT,Branded,756192001010,2021-10-28,Ham I Am! Inc.,HOGWASH,"BROWN SUGAR, HORSERADISH (HORSERADISH, DISTILL...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,173320,"Fast foods, cheeseburger; double, large patty;...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21396.0,NaN,NaN,NaN,NaN,NaN
2,173319,"Fast foods, cheeseburger; double, regular patt...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21395.0,NaN,NaN,NaN,NaN,NaN
3,172082,"Fast foods, cheeseburger; single, large patty;...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21398.0,NaN,NaN,NaN,NaN,NaN
4,170691,"Fast foods, cheeseburger; single, regular patt...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21090.0,NaN,NaN,NaN,NaN,NaN
5,170710,"Fast foods, hamburger, large, single patty, wi...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21202.0,NaN,NaN,NaN,NaN,NaN
6,170694,"Fast foods, hamburger; single, regular patty; ...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21108.0,NaN,NaN,NaN,NaN,NaN
7,173323,"Fast foods, bagel, with breakfast steak, egg, ...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21411.0,NaN,NaN,NaN,NaN,NaN
8,173322,"Fast foods, bagel, with egg, sausage patty, ch...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21410.0,NaN,NaN,NaN,NaN,NaN
9,170293,"Fast foods, cheeseburger, double, regular patt...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21094.0,NaN,NaN,NaN,NaN,NaN
10,170692,"Fast foods, cheeseburger; single, regular patt...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21091.0,NaN,NaN,NaN,NaN,NaN
11,172083,"Fast Foods, cheeseburger; double, large patty;...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21399.0,NaN,NaN,NaN,NaN,NaN
12,172081,"Fast foods, cheeseburger; single, large patty;...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21397.0,NaN,NaN,NaN,NaN,NaN
13,172080,"Fast foods, hamburger; double, large patty; wi...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21389.0,NaN,NaN,NaN,NaN,NaN
14,173317,"Fast foods, hamburger; single, large patty; wi...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21390.0,NaN,NaN,NaN,NaN,NaN
15,172084,"Fast foods, cheeseburger; double, regular patt...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21400.0,NaN,NaN,NaN,NaN,NaN
16,173318,"Fast foods, hamburger; single, regular patty; ...",SR Legacy,NaN,2019-04-01,NaN,NaN,NaN,NaN,Fast Foods,...,[],[],,,21393.0,NaN,NaN,NaN,NaN,NaN
17,2670119,"HABANERO CONDIMENT SAUCE, HABANERO CONDIMENT",Branded,856262005105,2023-11-16,RealStuff Inc.,YELLOWBIRD,"ORGANIC CARROTS, ONIONS, HABANERO PEPPERS, ORG...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
18,2587532,"HABANERO CONDIMENT SAUCE, HABANERO CONDIMENT",Branded,856262005235,2023-06-29,RealStuff Inc.,YELLOWBIRD,"ORGANIC CARROTS, ONIONS, HABANERO PEPPERS, ORG...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
19,2670117,"SERRANO CONDIMENT SAUCE, SERRANO CONDIMENT",Branded,856262005082,2023-11-16,RealStuff Inc.,YELLOWBIRD,"SERRANO PEPPERS, CUCUMBERS, ONIONS, ORGANIC CA...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
20,1850849,MEXICAN CONDIMENT,Branded,072212495134,2021-07-29,Linda's Food Products Inc.,DONA MARIA,"PUMPKIN SEEDS, SOYBEAN OIL, CRACKERS (WHEAT FL...",United States,"Oriental, Mexican & Ethnic Sauces",...,[],[],NaN,NaN,NaN,NaN,MOLE VERDE,NaN,NaN,NaN
21,1932010,TOMATO CONDIMENT,Branded,078883720001,2021-07-29,"Sabormex, S.A. de C.V.",CLEMENTE JACQUES,"TOMATO CONCENTRATE, HIGH FRUCTOSE CORN SYRUP, ...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2171000,VINEGAR WITH CONDIMENT,Branded,896211002502,2021-10-28,Global Garlic Inc.,DE MI PAIS,"WATER, ACETIC ACID (4%), SALT, FLAVORS OF GARL...",United States,Other Cooking Sauces,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2651802,COLORING & SEASONING CONDIMENT,Branded,0094262413432,2023-10-26,Bijol & Spices Inc.,BIJOL,"CORN FLOUR, CUMIN, ANNATTO, YELLOW NO. 5, RED ...",United States,Herbs & Spices,...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
24,2324841,COLORING & SEASONING CONDIMENT,Branded,094262413432,2022-06-21,Bijol & Spices Inc.,BIJOL,"CORN FLOUR, CUMIN, ANNATTO, YELLOW NO. 5 AND R...",United States,"Seasoning Mixes, Salts, Marinades & Tenderizers",...,[],[],NaN,NaN,NaN,,NaN,,This record previously showed no nutrient info...,NaN
25,2571698,COLORING & SEASONING CONDIMENT,Branded,0094262021569,2023-06-29,Bijol & Spices Inc.,BIJOL,"CORN FLOUR, CUMIN, ANNATTO, YELLOW NO. 5, RED ...",United States,"Seasoning Mixes, Salts, Marinades & Tenderizers",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
26,2445703,CONDIMENT ANNATTO PASTE,Branded,724195000569,2023-01-26,"Condimentos Y Productos Marin, Sa De Cv",MARIN,"WATER,ANNATTO SEED, CORN FLOUR, SALT, GARLIC, ...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
27,2032176,CONDIMENTED ANNATTO PASTE,Branded,816493010033,2021-10-28,GS1 Mexico,EL YUCATECO,"WATER, ANNATTO SEED, CORN FLOUR, SALT, GARLIC ...",United States,"Seasoning Mixes, Salts, Marinades & Tenderizers",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1061783,ORGANIC APPLE CONDIMENT,Branded,8032738590418,2020-07-30,ACETAIA GUERZONI SRL,NaN,"APPLE JUICE CONCENTRATED*, APPLE CIDER VINEGAR*.",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,"[{'name': 'Update Log', 'description': 'Change...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2392438,"RASPBERRY CONDIMENT, RASPBERRY",Branded,039632001512,2022-12-22,Big Five Software,ARISTON,"CONCENTRATED GRAPE JUICE, WINE VINEGAR, RASPBE...",United States,Salad Dressing & Mayonnaise,...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
30,2084181,WHITE BALSAMIC CONDIMENT,Branded,041253001833,2021-10-28,The Napoleon Co.,NAPOLEON,WHITE BALSAMIC VINEGAR. CONTAINS NATURALLY OCC...,United States,Other Condiments,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2399550,WHITE CONDIMENT OF MODENA,Branded,728119099493,2022-12-22,International Delicacies Inc.,CUCINA & AMORE,"WINE VINEGAR, RECTIFIED CONCENTRATED GRAPE MUS...",United States,Other Cooking Sauces,...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
32,2403925,ALL NATURAL CRUNCHY CONDIMENT,Branded,854430008002,2022-12-22,"Chile Colonial, LLC",CHILE CRUNCH,"NON-GMO CANOLA OIL, ONION, GARLIC, CHILES, SALT.",United States,"Seasoning Mixes, Salts, Marinades & Tenderizers",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
33,2119655,AUTHENTIC MOLE MEXICAN CONDIMENT,Branded,074734065130,2021-10-28,"Mercado Latino, Inc.",FARAON,"SOYBEAN OIL, SOYBEAN FLOUR, SUGAR, COOKIES (WH...",United States,"Oriental, Mexican & Ethnic Sauces",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2081690,"BOTTICELLI, GOLDEN BALSAMIC CONDIMENT",Branded,855019000271,2021-10-28,Botticelli Foods Corp.,BOTTICELLI,"WHITE WINE VINEGAR, CONCENTRATED GRAPE JUICE.",United States,Other Condiments,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2607212,CONDIMENT WHITE MODENA VINEGAR,Branded,0855019000271,2023-07-13,Botticelli Foods Corp.,BOTTICELLI,"WINE VINEGAR, CONCENTRATED GRAPE MUST",United States,Other Cooking Sauces,...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
36,2105378,FIG ORGANIC BALSAMIC CONDIMENT,Branded,048176660116,2021-10-28,Fratelli Mantova Fu Vincenzo,FRATELLI MANTOVA,ORGANIC BALSAMIC VINEGAR OF MODENA 99% (ORGANI...,United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2112175,GOURMET GARLIC CONDIMENT & SAUCE,Branded,040232124945,2021-10-28,Entertainment Production House Inc.,GARLISH,"CANOLA OIL, FRESH RAW GARLIC, LEMON JUICE CONC...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2039023,"ISOLA, WHITE ITALIAN CONDIMENT",Branded,780961000539,2021-10-28,"Isola Imports, Inc.",ISOLA,"WHITE WINE VINEGAR, CONCENTRATED GRAPE MUST.",United States,Salad Dressing & Mayonnaise,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2670118,"JALAPENO CONDIMENT SAUCE, JALAPENO",Branded,856262005099,2023-11-16,RealStuff Inc.,YELLOWBIRD,"JALAPENO PEPPERS, ORGANIC CARROTS, ORGANIC DIS...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
40,2153406,MEDITERRANEAN ZA'ATAR CONDIMENT & SPREAD,Branded,636947595257,2021-10-28,"Faux Fun, Inc.",ZESTY Z,"EXTRA VIRGIN OLIVE OIL, THYME, SUMAC, OREGANO,...",United States,Herbs & Spices,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2089416,OAXACA MEXICAN CONDIMENT SAUCE,Branded,044774108098,2021-10-28,"Bueno Alimentos, S.A.",DONA LUCIA,"SESAME SEED, VEGETABLE OIL(COTTONSEED AND/OR S...",United States,"Oriental, Mexican & Ethnic Sauces",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2698607,PACE CONDIMENTS MEDIUM SALSA,Branded,00041565275069,2024-07-11,CAMPBELL SOUP COMPANY,PACE,"INGREDIENTS: CRUSHED TOMATOES (WATER, CRUSHED ...",United States,Sauces/Spreads/Dips/Condiments,...,[],[],NaN,NaN,NaN,PACE MED SLSA SQZ,NaN,UNPREPARED,NaN,50171800.0
43,2698642,PACE CONDIMENTS MILD PICANTE,Branded,00041565275236,2024-07-11,CAMPBELL SOUP COMPANY,PACE,"INGREDIENTS: CRUSHED TOMATOES (WATER, CRUSHED ...",United States,Sauces/Spreads/Dips/Condiments,...,[],[],NaN,NaN,NaN,PACE MILD SLSA SQZ,NaN,UNPREPARED,NaN,50171800.0
44,2698625,PACE CONDIMENTS SALSA VERDE,Branded,00041565275076,2024-07-11,CAMPBELL SOUP COMPANY,PACE,"INGREDIENTS: YELLOW TOMATO PUREE (WATER, YELLO...",United States,Sauces/Spreads/Dips/Condiments,...,[],[],NaN,NaN,NaN,PACE SLSA VERDE SQZ,NaN,UNPREPARED,NaN,50171800.0
45,2057970,RASPBERRY ORGANIC BALSAMIC CONDIMENT,Branded,048176660314,2021-10-28,Fratelli Mantova Fu Vincenzo,FRATELLI MANTOVA,ORGANIC BALSAMIC VINEGAR OF MODENA 98% (ORGANI...,United States,Salad Dressing & Mayonnaise,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,1910980,"TRU SAMBAL, SPICE CONDIMENT",Branded,854220003019,2021-07-29,"Dr. Jill's Foot Pads, Inc.",TRU SAMBAL,"ONIONS/SHATTOT, CANOLA/VEGETABLE OIL, SUGAR, S...",United States,"Ketchup, Mustard, BBQ & Cheese Sauce",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2440352,"CHIMICHURRI MARINADE, CONDIMENT, DIPPING SAUCE",Branded,185544400018,2022-12-22,Cordoba Foods LLC,GAUCHO RANCH,"GARLIC, PARSLEY, NON-GMO SOYBEAN OIL, VINEGAR,...",United States,"Seasoning Mixes, Salts, Marinades & Tenderizers",...,[],[],NaN,NaN,NaN,,NaN,NaN,NaN,NaN
48,2008408,"DONA MARIA, MEXICAN CONDIMENT MOLE",Branded,072212505239,2021-10-28,Linda's Food Products Inc.,DONA MARIA,"SOYBEAN OIL, CRACKERS (WHEAT FLOUR, WHEAT BRAN...",United States,"Oriental, Mexican & Ethnic Sauces",...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2037202,"DONA MARIA, PIPIAN MEXICAN CONDIMENT",Branded,072878495233,2021-10-28,Herdez S.A.,DONA MARIA,"PUMPKIN SEED, SOYBEAN OIL, CRACKERS (WHEAT FLO...",United States,Other Cooking Sauces,...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN