# Get Bioavailable Iron from USDA

In [17]:
# Parameters
SAVE_DFS = True

In [18]:
import ast
import os
import pandas as pd
import requests

from dotenv import load_dotenv
from IPython.display import Image
from pathlib import Path
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [19]:
# Load splits from CSVs
df_train = pd.read_csv('../data/train/df_train.csv')
df_val = pd.read_csv('../data/val/df_val.csv')
df_test = pd.read_csv('../data/test/df_test.csv')

df_train.head(2)

,image_url,camera_or_phone_prob,food_prob,dish_name,food_type,ingredients,portion_size,nutritional_profile,cooking_method,sub_dt,image_name
0,https://file.b18a.io/7832973280900104501_54585...,0.8,0.90,oysters,homemade food,['oysters'],{'oysters': '500g'},"{'fat_g': 5.0, 'protein_g': 20.0, 'calories_kc...",raw,20250710,7832973280900104501_545859_.jpeg
1,https://file.b18a.io/7835136777400102715_70587...,0.7,0.95,grilled steak,restaurant food,"['steak', 'broccoli', 'potato', 'tomato', 'sau...","{'steak': '250g', 'broccoli': '50g', 'potato':...","{'fat_g': 30.0, 'protein_g': 50.0, 'calories_k...",grilling,20250702,7835136777400102715_705873_.jpeg

In [20]:
# Combine dfs
df_all = pd.concat([df_train, df_val, df_test])
df_all = df_all.reset_index()

df_all.shape

(5000, 12)

In [21]:
df_all['dish_name']

0                              oysters
1                        grilled steak
2              sweet and sour potatoes
3                              hot pot
4                   stir-fried noodles
                     ...
4995                       noodle soup
4996              braised chicken feet
4997                           hot pot
4998    vegetable and chicken sandwich
4999                mixed asian dishes
Name: dish_name, Length: 5000, dtype: object

In [22]:
df_all['portion_size'][0]

"{'oysters': '500g'}"

In [23]:
df_all['portion_size'] = df_all['portion_size'].apply(ast.literal_eval)

df_all['portion_size'][0]

{'oysters': '500g'}

In [24]:
# Get all ingredients
ingredients = set()
for row in df_all.itertuples():
    keys = row.portion_size.keys()
    ingredients.update(row.portion_size.keys())
print(f'{len(ingredients)=}')
ingredients

len(ingredients)=798

{'abalone',
 'almonds',
 'anchovies',
 'apple',
 'apple chips',
 'apples',
 'apricot',
 'apricots',
 'asparagus',
 'assorted desserts',
 'avocado',
 'baby corn',
 'bacon',
 'bagel',
 'baked beans',
 'baked goods',
 'baked potato',
 'baklava',
 'bamboo shoots',
 'banana',
 'bananas',
 'bao dough',
 'bar',
 'base',
 'basil',
 'batter',
 'bbq ribs',
 'bean sprouts',
 'beans',
 'beef',
 'beef liver',
 'beef patty',
 'beef ribs',
 'beef snack',
 'beef stew',
 'beef tripe',
 'beer',
 'beet',
 'beetroot',
 'beets',
 'bell pepper',
 'bell peppers',
 'berries',
 'beverage',
 'beverages',
 'bird',
 'birds',
 'biscuit',
 'biscuits',
 'bitter melon',
 'black beans',
 'black fungus',
 'black jelly',
 'black olive tapenade',
 'black pudding',
 'black rice',
 'black sapote',
 'blackberries',
 'blueberries',
 'boiled egg',
 'boiled eggs',
 'bok choy',
 'borscht',
 'bounty bar',
 'bread',
 'bread roll',
 'bread rolls',
 'breading',
 'brisket',
 'broad beans',
 'broccoli',
 'broth',
 'buckwheat',
 'bulgur',
 'bun',
 'buns',
 'burger',
 'burger patty',
 'butter',
 'cabbage',
 'cabbage rolls',
 'cake',
 'cakes',
 'calamari',
 'can',
 'candy',
 'canned beverage',
 'cantaloupe',
 'caramel sauce',
 'carrot',
 'carrots',
 'cashew nuts',
 'cashews',
 'cassava',
 'casserole',
 'cauliflower',
 'caviar',
 'celery',
 'century eggs',
 'cereal',
 'char siu',
 'cheddar cheese',
 'cheese',
 'cheese filling',
 'cheese sauce',
 'cheese sticks',
 'cheesecake',
 'cherries',
 'cherry',
 'cherry tomatoes',
 'chestnuts',
 'chicken',
 'chicken breast',
 'chicken drumstick',
 'chicken drumsticks',
 'chicken feet',
 'chicken leg',
 'chicken mcnuggets',
 'chicken nuggets',
 'chicken patty',
 'chicken skewers',
 'chicken strips',
 'chicken tenders',
 'chicken wing',
 'chicken wings',
 'chickpeas',
 'chili',
 'chili peppers',
 'chips',
 'chocolate',
 'chocolate bar',
 'chocolate cake',
 'chocolate ice cream',
 'chocolate roll cake',
 'chocolate sauce',
 'chocolate spread',
 'chocolate tart',
 'chutney',
 'cilantro',
 'clam',
 'clams',
 'coconut',
 'coconut drink',
 'coconut flour',
 'coconut jelly',
 'coconut milk',
 'coconut milk dessert',
 'coconut water',
 'coffee',
 'coffee beans',
 'coffee concentrate',
 'coffee sachet',
 'coleslaw',
 'condiment',
 'condiment1',
 'condiment2',
 'condiment3',
 'condiments',
 'cone',
 'cooked eggs',
 'cookie',
 'cookie cup',
 'cookie rolls',
 'cookies',
 'corn',
 'cottage cheese',
 'couscous',
 'crab',
 'crabs',
 'crackers',
 'cracklings',
 'cranberries',
 'crawfish',
 'crayfish',
 'cream',
 'cream base',
 'cream puff',
 'cream sauce',
 'cream tart',
 'creamy dip',
 'creamy sauce',
 'crepes',
 'crisps',
 'crispy cups',
 'crispy topping',
 'crispy toppings',
 'croissant',
 'croquettes',
 'croutons',
 'crust',
 'crème brûlée',
 'cucumber',
 'cucumbers',
 'cup',
 'cupcake',
 'cured meat',
 'curry',
 'curry bread',
 'custard',
 'cutlet',
 'daikon',
 'dairy',
 'dairy drink',
 'date',
 'dates',
 'dessert',
 'dessert cup',
 'desserts',
 'dip',
 'dipping sauce',
 'donut',
 'doritos',
 'dough',
 'dough balls',
 'dough sticks',
 'dragon fruit',
 'dressing',
 'dried chili',
 'dried chilies',
 'dried cranberries',
 'dried fruit',
 'dried fruits',
 'dried mushrooms',
 'dried plums',
 'dried tomatoes',
 'drink',
 'drink1',
 'drink2',
 'drink3',
 'drink4',
 'drinks',
 'duck',
 'dumpling',
 'dumpling wrapper',
 'dumplings',
 'durian',
 'edamame',
 'eel',
 'efo riro',
 'egg',
 'egg dish',
 'egg tart',
 'eggplant',
 'eggs',
 'energy drink',
 'espresso',
 'falafel',
 'fanta',
 'filet mignon',
 'filling',
 'fish',
 'fish cakes',
 'fish roe',
 'fish skin',
 'flan',
 'flatbread',
 'flour',
 'french fries',
 'french toast',
 'fried balls',
 'fried batter',
 'fried bread',
 'fried cakes',
 'fried chicken',
 'fried dish',
 'fried dough',
 'fried dough balls',
 'fried dough stick',
 'fried dough sticks',
 'fried dumplings',
 'fried egg',
 'fried eggplant',
 'fried elements',
 'fried fish',
 'fried item',
 'fried items',
 'fried meat',
 'fried nuggets',
 'fried onions',
 'fried pork',
 'fried pork cutlet',
 'fried potatoes',
 'fried rice',
 'fried rolls',
 'fried shrimp',
 'fried sides',
 'fried snack',
 'fried snacks',
 'fried tofu',
 'fried toppings',
 'fried vegetables',
 'fries',
 'fritter',
 'fritters',
 'frog legs',
 'frosting',
 'frozen fruit pop',
 'fruit',
 'fruit filling',
 'fruit mix',
 'fruit puree',
 'fruit smoothie',
 'fruit1',
 'fruit2',
 'fruits',
 'fudge',
 'fufu',
 'garlic',
 'garnish',
 'garnishes',
 'gelatin',
 'gelato',
 'ginger',
 'glaze',
 'glutinous rice',
 'glutinous rice balls',
 'gnocchi',
 'goat milk powder',
 'goji berries',
 'grains',
 'granola',
 'grape leaves',
 'grapefruit',
 'grapes',
 'gravy',
 'green apples',
 'green beans',
 'green bell pepper',
 'green cake',
 'green chili',
 'green chilies',
 'green grapes',
 'green onion',
 'green onions',
 'green peas',
 'green pepper',
 'green peppers',
 'green tea',
 'green tea ice cream',
 'green vegetables',
 'greens',
 'grilled chicken',
 'grilled eel',
 'grilled fish',
 'grilled lemon',
 'grilled meat',
 'grilled squash',
 'ground beef',
 'ground meat',
 'ground pork',
 'gummy bears',
 'ham',
 'hamburger patty',
 'hamburger steak',
 'hash browns',
 'hawthorn',
 'herbs',
 'honey',
 'honeycomb',
 'hot dog',
 'hot dogs',
 'hot pot',
 'hot pot ingredients',
 'hummus',
 'ice',
 'ice cream',
 'ice cream bar',
 'insects',
 'jackfruit',
 'jelly',
 'juice',
 'jujube',
 'jujubes',
 'kale',
 'kataifi',
 'kebab',
 'kebabs',
 'kefir',
 'ketchup',
 'kibble',
 'kimchi',
 'kiwi',
 'kiwifruit',
 'kozinaki',
 'lamb',
 'lamb chops',
 'lasagna',
 'leaf',
 'leafy greens',
 'leaves',
 'leeks',
 'legumes',
 'lemon',
 'lemons',
 'lentil curry',
 'lentils',
 'lettuce',
 'lime',
 'liver',
 'lobster',
 'lollipops',
 'longan',
 'loquat',
 'lotus root',
 'lotus root slices',
 'lychee',
 'macaron',
 'mackerel',
 'madeleines',
 'main dish',
 'main ingredient',
 'mango',
 'mangosteen',
 'marshmallows',
 'mashed potatoes',
 'matcha',
 'matcha cream',
 'mayonnaise',
 'mcspicy wings',
 'meat',
 'meat dish',
 'meat filling',
 'meat patty',
 'meat sauce',
 'meat skewers',
 'meat topping',
 'meatball',
 'meatballs',
 'meatloaf',
 'melon',
 'melon seeds',
 'meringue',
 'milk',
 'milk tea',
 'minced meat',
 'mini cakes',
 'mint',
 'mint candy',
 'mint ice cream',
 'mix',
 'mixed dish',
 'mixed fruits',
 'mixed vegetables',
 'mochi',
 'momos',
 'morning glory',
 'mozzarella',
 'mozzarella sticks',
 'muffin',
 'mulberries',
 'mung beans',
 'mushrooms',
 'mussels',
 'mustard',
 'naan',
 'nabati',
 'nachos',
 'nectarine',
 'nextar',
 'noodle dish',
 'noodle soup',
 'noodles',
 'nori',
 'nougat',
 'nuts',
 'oat milk',
 'oat snack',
 'oatmeal',
 'oats',
 'octopus',
 'oil',
 'okra',
 'olive oil',
 'olives',
 'omelet',
 'onion',
 'onion rings',
 'onions',
 'orange',
 'orange juice',
 'orange pepper',
 'oranges',
 'oreo',
 'organ meat',
 'other dishes',
 'other ingredients',
 'other vegetables',
 'oysters',
 'pakoras',
 'pancake',
 'pancakes',
 'panna cotta',
 'papaya',
 'parsley',
 'passion fruit',
 'pasta',
 'pasta shells',
 'pastries',
 'pastry',
 'pastry crust',
 'pastry1',
 'pastry2',
 'pastry3',
 'pastry4',
 'patties',
 'patty',
 'peach',
 'peach slices',
 'peaches',
 'peanut butter',
 'peanut sauce',
 'peanuts',
 'pear',
 'pears',
 'peas',
 'pecans',
 'pepper',
 'peppers',
 'pesto',
 'pickled fish',
 'pickled radish',
 'pickled vegetables',
 'pickles',
 'pie',
 'pine nuts',
 'pineapple',
 'pistachio tart',
 'pistachios',
 'pizza',
 'pizza slice',
 'plantain',
 'plantain chips',
 'plantains',
 'plum',
 'plums',
 'poached egg',
 'pomegranate',
 'pomelo',
 'popcorn',
 'popsicle',
 'pork',
 'pork belly',
 'pork bits',
 'pork brain',
 'pork bun',
 'pork floss',
 'pork head',
 'pork hock',
 'pork hocks',
 'pork knuckle',
 'pork ribs',
 'pork trotters',
 'porridge',
 'potato',
 'potato chips',
 'potato sticks',
 'potato wedge',
 'potatoes',
 'pounded yam',
 'powder',
 'preserved egg',
 'processed meat',
 'protein',
 'protein drink',
 'protein source',
 'pudding',
 'puff pastry',
 'pumpkin',
 'pumpkin seeds',
 'puri',
 'purple yam',
 'quinoa',
 'radish',
 'radishes',
 'raisins',
 'rambutan',
 'rasgulla',
 'raspberries',
 'raspberry',
 'raw vegetables',
 'red apples',
 'red bean paste',
 'red beans',
 'red bell pepper',
 'red chili',
 'red chilies',
 'red currants',
 'red grapes',
 'red pepper',
 'red peppers',
 'ribs',
 'rice',
 'rice cake',
 'rice cakes',
 'rice flour',
 'rice noodles',
 'rice paper',
 'rice porridge',
 'rice rolls',
 'ricotta',
 'roast meat',
 'roasted chicken',
 'roasted duck',
 'roasted meat',
 'roasted potatoes',
 'roll',
 'rolled meat',
 'rolls',
 'root vegetables',
 'roti',
 'rye bread',
 'sago',
 'salad',
 'salad greens',
 'salmon',
 'salmon sushi',
 'salsa',
 'sambal',
 'samosa',
 'samosas',
 'sandwich',
 'sashimi',
 'sauce',
 'sauces',
 'sauerkraut',
 'sausage',
 'sausages',
 'savory pancake',
 'savory snack',
 'scallions',
 'scallop',
 'scallops',
 'scrambled eggs',
 'sea urchin',
 'seafood',
 'seafood skewers',
 'seafood stew',
 'seafood topping',
 'seasoning',
 'seaweed',
 'seeds',
 'semolina',
 'sesame',
 'sesame bread',
 'sesame seeds',
 'shaved ice',
 'shellfish',
 'short ribs',
 'shortbread',
 'shredded crab',
 'shredded meat',
 'shredded vegetables',
 'shrimp',
 'shrimp dish',
 'shrimp dumpling',
 'shrimp porridge',
 'side',
 'side dish',
 'side dishes',
 'side item',
 'side salad',
 'side vegetables',
 'sides',
 'skewered meat',
 'skewers',
 'skittles',
 'sliced meat',
 'small fish',
 'smoked salmon',
 'smoothie',
 'snack',
 'snack balls',
 'snack mix',
 'snack sticks',
 'snack1',
 'snack2',
 'snack3',
 'snacks',
 'snails',
 'snap peas',
 'soba noodles',
 'soda',
 'soup',
 'soup base',
 'sour cream',
 'soy milk',
 'soy sauce',
 'soybeans',
 'soymilk',
 'spaghetti',
 'spice mix',
 'spices',
 'spinach',
 'split peas',
 'sponge cake',
 'spread',
 'spring roll',
 'spring rolls',
 'sprouts',
 'squash',
 'squid',
 'starch',
 'starchy side',
 'starfruit',
 'steak',
 'steamed buns',
 'steamed vegetables',
 'stew',
 'sticks',
 'sticky rice',
 'stir-fried chicken',
 'stir-fried vegetables',
 'stir-fried vegetables and meat',
 'stir-fry',
 'strawberries',
 'strawberry',
 'stuffing',
 'sugar',
 'sugar syrup',
 'sun-dried tomatoes',
 'sunflower seeds',
 'sushi',
 'sushi rice',
 'sushi roll',
 'sweet bread',
 'sweet dish',
 'sweet paste',
 'sweet potato',
 'sweet potatoes',
 'sweet soup',
 'sweet toppings',
 'sweet treat',
 'sweetener',
 'swiss roll',
 'syrup',
 'tacos',
 'tangerine',
 'tapioca',
 'tapioca balls',
 'tapioca pearls',
 'taro cake',
 'tart',
 'tart base',
 'tart crust',
 'tea',
 'tea bag',
 'tea leaves',
 'tempeh',
 'tempura',
 'toast',
 'tofu',
 'tomato',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'topping',
 'toppings',
 'tortilla',
 'tortilla chips',
 'tortillas',
 'tuna',
 'tuna sushi',
 'turkey',
 'twix',
 'udon',
 'vegetable bites',
 'vegetable curry',
 'vegetable dish',
 'vegetable mixture',
 'vegetable pancake',
 'vegetable sauce',
 'vegetable skewers',
 'vegetable stew',
 'vegetable stir-fry',
 'vegetables',
 'wafer',
 'wafer cone',
 'wafer sticks',
 'waffle',
 'waffles',
 'walnut',
 'walnut milk',
 'wasabi',
 'water',
 'watermelon',
 'watermelon candy',
 'whipped cream',
 'whole grain bread',
 'wontons',
 'wood ear mushrooms',
 'wrap',
 'wrapper',
 'yakult',
 'yams',
 'yeast',
 'yellow cherries',
 'yogurt',
 'zucchini'}

In [25]:
nutrient_names = ['Iron, Fe', 'Calcium, Ca', 'Vitamin C, total ascorbic acid']

ingredients_df = {'ingredients': list(ingredients)}
ingredients_df = pd.DataFrame(ingredients_df)
for name in nutrient_names:
    ingredients_df[name] = ''
ingredients_df

      ingredients Iron, Fe Calcium, Ca Vitamin C, total ascorbic acid
0           crabs
1        beetroot
2         coconut
3      sea urchin
4    pasta shells
..            ...      ...         ...                            ...
793     meat dish
794    cantaloupe
795         crust
796    pork floss
797      dressing

[798 rows x 4 columns]

In [26]:
csv_file = '../data/ingredients.csv'

if SAVE_DFS:
    # Save to CSV
    ingredients_df.to_csv(csv_file, index=False)

# Load data from previously saved CSV
ingredients_df = pd.read_csv(csv_file)
ingredients_df

      ingredients  Iron, Fe  Calcium, Ca  Vitamin C, total ascorbic acid
0           crabs       NaN          NaN                             NaN
1        beetroot       NaN          NaN                             NaN
2         coconut       NaN          NaN                             NaN
3      sea urchin       NaN          NaN                             NaN
4    pasta shells       NaN          NaN                             NaN
..            ...       ...          ...                             ...
793     meat dish       NaN          NaN                             NaN
794    cantaloupe       NaN          NaN                             NaN
795         crust       NaN          NaN                             NaN
796    pork floss       NaN          NaN                             NaN
797      dressing       NaN          NaN                             NaN

[798 rows x 4 columns]

## USDA FoodData Central API

In [27]:
# Load and get api key from .env
load_dotenv()
api_key = os.getenv("API_KEY")

FOODS_SEARCH_URL = 'https://api.nal.usda.gov/fdc/v1/foods/search'

In [28]:
# Search for food
ingredient = 'abalone'
food_query = ingredient
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
data = r.json()
data_df = pd.DataFrame.from_dict(data['foods'])
if len(data_df) == 0:  # Data not found
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
data_df

,fdcId,description,commonNames,additionalDescriptions,dataType,foodCode,publishedDate,foodCategory,foodCategoryId,allHighlightFields,...,marketCountry,modifiedDate,dataSource,servingSizeUnit,servingSize,householdServingFullText,tradeChannels,brandName,packageWeight,shortDescription
0,2706337,Abalone,,,Survey (FNDDS),26301110.0,2024-10-31,Shellfish,3300222.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,174212,"Mollusks, abalone, mixed species, raw",,,SR Legacy,NaN,2019-04-01,Finfish and Shellfish Products,NaN,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,174213,"Mollusks, abalone, mixed species, cooked, fried",,,SR Legacy,NaN,2019-04-01,Finfish and Shellfish Products,NaN,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,552097,RICE PORRIDGE WITH ABALONE,NaN,NaN,Branded,NaN,2019-04-01,Other Soups,NaN,"<b>Ingredients</b>: WATER, RICE, <em>ABALONE</...",...,United States,2017-11-09,LI,g,285.0,10.05 ONZ,[NO_TRADE_CHANNEL],NaN,NaN,NaN
4,2085344,"NO. 1, WHOLE ABALONE MUSHROOM",NaN,NaN,Branded,NaN,2021-10-28,Canned Vegetables,NaN,<b>Ingredients</b>: <em>ABALONE</em> MUSHROOM ...,...,United States,2017-06-25,LI,g,100.0,13 PEASE,[NO_TRADE_CHANNEL],NO. 1,15 oz/425 g,NaN
5,2014577,"CALIFORNIA GIRL, IMITATION ABALONE",NaN,NaN,Branded,NaN,2021-10-28,Canned Seafood,NaN,,...,United States,2018-07-10,LI,g,55.0,0.5 cup,[NO_TRADE_CHANNEL],CALIFORNIA GIRL,15 oz/425 g,NaN
6,2176844,"WILD CAUGHT IMITATION ABALONE, WILD CAUGHT",NaN,NaN,Branded,NaN,2021-10-28,Canned Seafood,NaN,"<b>Ingredients</b>: CALAMARI, <em>ABALONE</em>...",...,United States,2021-04-23,LI,g,53.0,1/4 cup,[NO_TRADE_CHANNEL],SOL-MEX,15 OZ/425 G,NaN
7,2182958,Moana Select Harvest New Zealand Blue Abalone ...,NaN,NaN,Branded,NaN,2021-10-28,Seafood Miscellaneous,NaN,,...,New Zealand,2021-06-18,NZGDSN,g,45.0,None,[NO_TRADE_CHANNEL],Moana,200g,NaN
8,2070186,"WOODSTOCK, ORGANIC MIXED MUSHROOMS",NaN,NaN,Branded,NaN,2021-10-28,Frozen Vegetables,NaN,<b>Ingredients</b>: ORGANIC SHIITAKE MUSHROOMS...,...,United States,2017-07-14,LI,g,100.0,0.5 cup,[NO_TRADE_CHANNEL],WOODSTOCK,10 oz/283 g,NaN
9,2388182,"STIR FRY VEGETABLES, STIR FRY",NaN,NaN,Branded,NaN,2022-12-22,Canned Vegetables,NaN,"<b>Ingredients</b>: BEAN SPROUTS, BAMBOO SHOOT...",...,United States,2020-10-26,LI,g,230.0,1 can drained,[NO_TRADE_CHANNEL],ASIAN GOURMET,14 oz/397 G,

In [29]:
# Get food nutrients
nutrients = pd.DataFrame(data_df.iloc[0]['foodNutrients'])
print('Iron, Fe' in list(nutrients['nutrientName']))
nutrients = nutrients.loc[nutrients['nutrientName'].isin(nutrient_names)][['nutrientName', 'value']]
nutrients

True

                      nutrientName  value
10                     Calcium, Ca  39.00
11                        Iron, Fe   3.97
28  Vitamin C, total ascorbic acid   2.00

In [30]:
for row in nutrients.itertuples():
    print(row)
    ingredients_df.loc[ingredients_df['ingredients']==ingredient, row.nutrientName] = row.value
ingredients_df.loc[ingredients_df['ingredients']==ingredient]

Pandas(Index=10, nutrientName='Calcium, Ca', value=39.0)
Pandas(Index=11, nutrientName='Iron, Fe', value=3.97)
Pandas(Index=28, nutrientName='Vitamin C, total ascorbic acid', value=2.0)

    ingredients  Iron, Fe  Calcium, Ca  Vitamin C, total ascorbic acid
575     abalone      3.97         39.0                             2.0

In [31]:
def get_nutrients(data_df, ingredients_df, nutrient_names):
    if len(data_df) > 0:  # Food found
        nutrients = pd.DataFrame()
        i = 0
        while len(nutrients) == 0 and i < len(data_df):  # Look for entry with nutrients
            nutrients = pd.DataFrame(data_df.iloc[i]['foodNutrients'])
            i += 1
            if len(nutrients) > 0:  # Nutrients found
                nutrients = nutrients.loc[nutrients['nutrientName'].isin(nutrient_names)][['nutrientName', 'value']]
                if len(nutrients) == 0:  # Skip if no desired nutrients
                    continue
                for row in nutrients.itertuples():
                    ingredients_df.loc[ingredients_df['ingredients']==ingredient, row.nutrientName] = row.value
                ingredients_df.loc[ingredients_df['ingredients']==ingredient, 'found'] = True
                break
    return ingredients_df

In [ ]:
# Fill CSV with nutrient data for ingredients
csv_file = '../data/ingredients_auto.csv'
ingredients_df['found'] = False

for ingredient in tqdm(ingredients):
    # Search for food
    food_query = ingredient
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
    # Get food nutrients
    ingredients_df = get_nutrients(data_df, ingredients_df, nutrient_names)

    # Check if food not found earlier, broaden food search
    if ingredients_df.loc[ingredients_df['ingredients']==ingredient]['found'].item() == False:
        r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
        data = r.json()
        data_df = pd.DataFrame.from_dict(data['foods'])
        # Get food nutrients
        ingredients_df = get_nutrients(data_df, ingredients_df, nutrient_names)

    if SAVE_DFS:
        # Save to CSV
        ingredients_df.to_csv(csv_file, index=False)

# Load data from previously saved CSV
ingredients_df = pd.read_csv(csv_file)
ingredients_df

  1%|          | 9/798 [00:05<07:44,  1.70it/s]

In [ ]:
ingredients_df.loc[ingredients_df['found']==False]

    ingredients  Iron, Fe  Calcium, Ca  Vitamin C, total ascorbic acid  found
8        drink1       NaN          NaN                             NaN  False
31   condiment1       NaN          NaN                             NaN  False
51      pastry4       NaN          NaN                             NaN  False
75     efo riro       NaN          NaN                             NaN  False
143  condiment2       NaN          NaN                             NaN  False
189      drink2       NaN          NaN                             NaN  False
223     pastry1       NaN          NaN                             NaN  False
246     pastry2       NaN          NaN                             NaN  False
306      snack3       NaN          NaN                             NaN  False
359      nextar       NaN          NaN                             NaN  False
363      fruit2       NaN          NaN                             NaN  False
525     pastry3       NaN          NaN                             NaN  False
533      drink3       NaN          NaN                             NaN  False
537      drink4       NaN          NaN                             NaN  False
562      snack2       NaN          NaN                             NaN  False
574    porridge       NaN          NaN                             NaN  False
607  condiment3       NaN          NaN                             NaN  False
658    rasgulla       NaN          NaN                             NaN  False
756    kozinaki       NaN          NaN                             NaN  False
769      snack1       NaN          NaN                             NaN  False

In [ ]:
# Search for food
ingredient = 'porridge'
food_query = ingredient
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
data = r.json()
data_df = pd.DataFrame.from_dict(data['foods'])
if len(data_df) == 0:  # Data not found
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
data_df

,fdcId,description,dataType,publishedDate,tags,allHighlightFields,score,microbes,foodNutrients,finalFoodInputFoods,...,packageWeight,servingSizeUnit,servingSize,householdServingFullText,shortDescription,tradeChannels,commonNames,additionalDescriptions,foodCode,foodCategoryId
0,2687788,Potential of moringa leaf and baobab fruit foo...,Experimental,2024-04-18,"[Processing, Post-Harvest, USDA Research]",,303.968050,[],[],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2417422,"MULTIGRAIN PORRIDGE SLICED BREAD, TARTINE MULT...",Branded,2022-12-22,NaN,,230.002460,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2 oz/500 g,g,50.0,1 slice,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
2,2089884,ARTIFICIAL CHICKEN PORRIDGE,Branded,2021-10-28,NaN,<b>Ingredients</b>: <em>PORRIDGE</em> (52%): R...,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,4.2 oz/120 g,g,120.0,1 BOWL,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
3,2168938,ORGANIC PORRIDGE OATS,Branded,2021-10-28,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,35 oz/2.19 LB/992 g,g,40.0,1/2 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
4,1002697,PUMPKIN PORRIDGE WITH HONEY,Branded,2020-06-26,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
5,552097,RICE PORRIDGE WITH ABALONE,Branded,2019-04-01,NaN,,202.842590,[],"[{'nutrientId': 1004, 'nutrientName': 'Total l...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
6,552435,RICE PORRIDGE WITH TUNA,Branded,2019-04-01,NaN,,202.842590,[],"[{'nutrientId': 1087, 'nutrientName': 'Calcium...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
7,560546,RICE PORRIDGE WITH VEGETABLE,Branded,2019-04-01,NaN,,202.842590,[],"[{'nutrientId': 1004, 'nutrientName': 'Total l...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
8,2089623,SUPER SMOOTH PORRIDGE,Branded,2021-10-28,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,100.0,100 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
9,2432400,"TEFF PORRIDGE, IVORY",Branded,2022-12-22,NaN,,202.842590,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,5 oz/142 g,g,50.0,0.25 cup,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
10,2642126,"CORNMEAL INSTANT PORRIDGE, CORNMEAL",Branded,2023-09-14,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2.1 oz/60 g,GRM,60.0,1 container,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
11,2132017,"CORNMEAL INSTANT PORRIDGE, PEANUT",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,60 g/2.10 oz,g,60.0,60 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
12,2055230,"OATMEAL INSTANT PORRIDGE, BANANA",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,74 g/2.6 oz,g,74.0,74 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
13,2035067,"OTTOGI, VEGETABLE RICE PORRIDGE",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,34.0,2.5 Tbsp,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
14,2111605,"PAMANA, CHICKEN RICE PORRIDGE",Branded,2021-10-28,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,1.7 oz/48 g,g,48.0,1 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
15,2317368,Pams Creamy Porridge 850g,Branded,2022-05-23,NaN,,153.607360,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,850g,g,45.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
16,510622,CHAO CA FISH INSTANT PORRIDGE,Branded,2019-04-01,NaN,<b>Ingredients</b>: <em>PORRIDGE</em> (51.2%):...,111.640500,[],"[{'nutrientId': 1079, 'nutrientName': 'Fiber, ...",[],...,NaN,g,120.0,1 BOWL,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
17,2132824,"CINNAMON CORNMEAL INSTANT PORRIDGE, CINNAMON",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,60 g/2.10 oz,g,60.0,60 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
18,2114466,"OAT MEAL INSTANT PORRIDGE, ALMOND",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,74 g/2.6 oz,g,74.0,74 GRM,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
19,2035053,"OTTOGI, BLACK SESAME RICE PORRIDGE",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,32.0,2.5 Tbsp,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
20,2037377,"OTTOGI, SWEET RED BEAN PORRIDGE",Branded,2021-10-28,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,285.0,1 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
21,1002425,SWEET RED BEAN AND CHESTNUT PORRIDGE,Branded,2020-06-26,NaN,,111.640500,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,NaN,g,285.0,10.05 ONZ,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
22,2642127,"GREEN BANANA INSTANT PORRIDGE, GREEN BANANA",Branded,2023-09-14,NaN,,75.443140,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,1.9 oz/55 g,GRM,55.0,1 container,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
23,2108195,"PAMANA, MUNG BEAN PORRIDGE WITH COCONUT MILK",Branded,2021-10-28,NaN,,75.443140,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2.65 oz/75 g,g,75.0,1 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
24,2288195,"PAMANA, GINATAANG MAIS, CORN PORRIDGE WITH COC...",Branded,2022-05-23,NaN,,43.901890,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,2.65 oz,g,75.0,1 cup,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
25,2182865,Pure Delish Bircher Porridge Creamy Chia 400g,Branded,2021-10-28,NaN,,43.901890,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,400g,g,40.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
26,2182866,Pure Delish Bircher Porridge Wild Blueberry 400g,Branded,2021-10-28,NaN,,43.901890,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,400g,g,40.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
27,2708418,Congee,Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gruel,26.327248,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Beverages, water, tap, d...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel,56205101.0,3304384.0
28,2708984,"Congee, with egg",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gruel,26.327248,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Eggs, Grade A, Large, eg...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel,58157330.0,3305516.0
29,2015623,"OLD WESSEX LTD., SCOTTISH-STYLE PORRIDGE OATS ...",Branded,2021-10-28,NaN,<b>Ingredients</b>: 100% NATURAL SCOTTISH-STYL...,25.215652,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,18.5 oz/524 g,g,40.0,0.5 cup,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
30,2708981,"Congee, with meat, poultry, and/or seafood",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: with egg;rice <em>porridge</e...,24.450163,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Salt, table', 'gramWeigh...",...,NaN,NaN,NaN,NaN,NaN,NaN,,with egg;rice porridge or gruel,58157300.0,3305510.0
31,2708982,"Congee, with meat, poultry, and/or seafood, an...",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gru...,24.450163,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Congee, with meat, poult...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel;with egg,58157310.0,3305512.0
32,2708983,"Congee, with vegetables",Survey (FNDDS),2024-10-31,NaN,<b>Includes</b>: rice <em>porridge</em> or gru...,24.450163,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...","[{'foodDescription': 'Rice, white, long-grain,...",...,NaN,NaN,NaN,NaN,NaN,NaN,,rice porridge or gruel;with beans,58157320.0,3305514.0
33,2182880,Pure Delish Bircher Porridge Dark Chocolate & ...,Branded,2021-10-28,NaN,,16.172852,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,400g,g,40.0,None,NaN,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN
34,2440243,JUMBO OATS,Branded,2022-12-22,NaN,<b>Ingredients</b>: PURE SCOTTISH <em>PORRIDGE...,-397.155670,[],"[{'nutrientId': 1003, 'nutrientName': 'Protein...",[],...,750 g,g,40.0,1 cup,,[NO_TRADE_CHANNEL],NaN,NaN,NaN,NaN