# Get Bioavailable Iron from USDA

In [59]:
# Parameters
SAVE_DFS = False

In [60]:
import ast
import os
import pandas as pd
import requests

from dotenv import load_dotenv
from IPython.display import Image
from pathlib import Path
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [61]:
# Load splits from CSVs
df_train = pd.read_csv('../data/train/df_train.csv')
df_val = pd.read_csv('../data/val/df_val.csv')
df_test = pd.read_csv('../data/test/df_test.csv')

df_train.head(2)

,image_url,camera_or_phone_prob,food_prob,dish_name,food_type,ingredients,portion_size,nutritional_profile,cooking_method,sub_dt,image_name
0,https://file.b18a.io/7832973280900104501_54585...,0.8,0.90,oysters,homemade food,['oysters'],{'oysters': '500g'},"{'fat_g': 5.0, 'protein_g': 20.0, 'calories_kc...",raw,20250710,7832973280900104501_545859_.jpeg
1,https://file.b18a.io/7835136777400102715_70587...,0.7,0.95,grilled steak,restaurant food,"['steak', 'broccoli', 'potato', 'tomato', 'sau...","{'steak': '250g', 'broccoli': '50g', 'potato':...","{'fat_g': 30.0, 'protein_g': 50.0, 'calories_k...",grilling,20250702,7835136777400102715_705873_.jpeg

In [62]:
# Combine dfs
df_all = pd.concat([df_train, df_val, df_test])
df_all = df_all.reset_index()

df_all.shape

(5000, 12)

In [123]:
df_all['dish_name']

0                              oysters
1                        grilled steak
2              sweet and sour potatoes
3                              hot pot
4                   stir-fried noodles
                     ...
4995                       noodle soup
4996              braised chicken feet
4997                           hot pot
4998    vegetable and chicken sandwich
4999                mixed asian dishes
Name: dish_name, Length: 5000, dtype: object

In [63]:
df_all['portion_size'][0]

"{'oysters': '500g'}"

In [64]:
df_all['portion_size'] = df_all['portion_size'].apply(ast.literal_eval)

df_all['portion_size'][0]

{'oysters': '500g'}

In [65]:
# Get all ingredients
ingredients = set()
for row in df_all.itertuples():
    keys = row.portion_size.keys()
    ingredients.update(row.portion_size.keys())
print(f'{len(ingredients)=}')
ingredients

len(ingredients)=822

{'abalone',
 'almonds',
 'anchovies',
 'apple',
 'apple chips',
 'apples',
 'apricot',
 'apricots',
 'asparagus',
 'assorted desserts',
 'avocado',
 'baby corn',
 'bacon',
 'bagel',
 'baked beans',
 'baked goods',
 'baked potato',
 'baklava',
 'bamboo shoots',
 'banana',
 'bananas',
 'bao dough',
 'bar',
 'base',
 'basil',
 'batter',
 'bbq ribs',
 'bean sprouts',
 'beans',
 'beef',
 'beef liver',
 'beef patty',
 'beef ribs',
 'beef stew',
 'beef tripe',
 'beef_snack',
 'beer',
 'beet',
 'beetroot',
 'beets',
 'bell pepper',
 'bell peppers',
 'berries',
 'beverage',
 'beverages',
 'bird',
 'birds',
 'biscuit',
 'biscuits',
 'bitter melon',
 'black beans',
 'black fungus',
 'black jelly',
 'black olive tapenade',
 'black pudding',
 'black rice',
 'black sapote',
 'blackberries',
 'blueberries',
 'boiled egg',
 'boiled eggs',
 'bok choy',
 'borscht',
 'bounty bar',
 'bread',
 'bread roll',
 'bread rolls',
 'bread_roll',
 'breading',
 'brisket',
 'broad beans',
 'broccoli',
 'broth',
 'buckwheat',
 'bulgur',
 'bun',
 'buns',
 'burger',
 'burger patty',
 'butter',
 'cabbage',
 'cabbage rolls',
 'cake',
 'cakes',
 'calamari',
 'can',
 'candy',
 'canned beverage',
 'cantaloupe',
 'caramel sauce',
 'carrot',
 'carrots',
 'cashew nuts',
 'cashews',
 'cassava',
 'casserole',
 'cauliflower',
 'caviar',
 'celery',
 'century eggs',
 'cereal',
 'char siu',
 'cheddar cheese',
 'cheese',
 'cheese filling',
 'cheese sauce',
 'cheese sticks',
 'cheesecake',
 'cherries',
 'cherry',
 'cherry tomatoes',
 'chestnuts',
 'chicken',
 'chicken breast',
 'chicken drumstick',
 'chicken drumsticks',
 'chicken feet',
 'chicken leg',
 'chicken mcnuggets',
 'chicken nuggets',
 'chicken patty',
 'chicken skewers',
 'chicken strips',
 'chicken wings',
 'chicken_leg',
 'chicken_tenders',
 'chicken_wing',
 'chicken_wings',
 'chickpeas',
 'chili',
 'chili peppers',
 'chips',
 'chocolate',
 'chocolate bar',
 'chocolate cake',
 'chocolate ice cream',
 'chocolate roll cake',
 'chocolate sauce',
 'chocolate spread',
 'chocolate tart',
 'chocolate_bar',
 'chutney',
 'cilantro',
 'clam',
 'clams',
 'coconut',
 'coconut drink',
 'coconut flour',
 'coconut jelly',
 'coconut milk',
 'coconut milk dessert',
 'coconut water',
 'coffee',
 'coffee beans',
 'coffee concentrate',
 'coffee_beans',
 'coffee_sachet',
 'coleslaw',
 'condiment',
 'condiment1',
 'condiment2',
 'condiment3',
 'condiments',
 'cone',
 'cooked eggs',
 'cookie',
 'cookie rolls',
 'cookie_cup',
 'cookies',
 'corn',
 'cottage cheese',
 'couscous',
 'crab',
 'crabs',
 'crackers',
 'cracklings',
 'cranberries',
 'crawfish',
 'crayfish',
 'cream',
 'cream puff',
 'cream sauce',
 'cream tart',
 'cream_base',
 'creamy dip',
 'creamy sauce',
 'crepes',
 'crisps',
 'crispy cups',
 'crispy topping',
 'crispy toppings',
 'croissant',
 'croquettes',
 'croutons',
 'crust',
 'crème brûlée',
 'cucumber',
 'cucumbers',
 'cup',
 'cupcake',
 'cured meat',
 'curry',
 'curry bread',
 'custard',
 'cutlet',
 'daikon',
 'dairy',
 'dairy drink',
 'date',
 'dates',
 'dessert',
 'dessert_cup',
 'desserts',
 'dip',
 'dipping sauce',
 'donut',
 'doritos',
 'dough',
 'dough balls',
 'dough_sticks',
 'dragon fruit',
 'dressing',
 'dried chili',
 'dried chilies',
 'dried cranberries',
 'dried fruit',
 'dried fruits',
 'dried mushrooms',
 'dried plums',
 'dried tomatoes',
 'drink',
 'drink1',
 'drink2',
 'drink3',
 'drink4',
 'drinks',
 'duck',
 'dumpling',
 'dumpling wrapper',
 'dumplings',
 'durian',
 'edamame',
 'eel',
 'efo riro',
 'egg',
 'egg dish',
 'egg tart',
 'eggplant',
 'eggs',
 'energy drink',
 'espresso',
 'falafel',
 'fanta',
 'filet mignon',
 'filling',
 'fish',
 'fish cakes',
 'fish roe',
 'fish skin',
 'flan',
 'flatbread',
 'flour',
 'french fries',
 'french toast',
 'fried balls',
 'fried batter',
 'fried bread',
 'fried cakes',
 'fried chicken',
 'fried dough',
 'fried dough balls',
 'fried dough stick',
 'fried dough sticks',
 'fried dumplings',
 'fried egg',
 'fried eggplant',
 'fried elements',
 'fried fish',
 'fried item',
 'fried items',
 'fried meat',
 'fried nuggets',
 'fried onions',
 'fried pork',
 'fried pork cutlet',
 'fried potatoes',
 'fried rice',
 'fried rolls',
 'fried shrimp',
 'fried sides',
 'fried snack',
 'fried snacks',
 'fried tofu',
 'fried toppings',
 'fried vegetables',
 'fried_dish',
 'fried_items',
 'fries',
 'fritter',
 'fritters',
 'frog legs',
 'frosting',
 'frozen fruit pop',
 'fruit',
 'fruit filling',
 'fruit mix',
 'fruit puree',
 'fruit smoothie',
 'fruit1',
 'fruit2',
 'fruits',
 'fudge',
 'fufu',
 'garlic',
 'garnish',
 'garnishes',
 'gelatin',
 'gelato',
 'ginger',
 'glaze',
 'glutinous rice',
 'glutinous rice balls',
 'gnocchi',
 'goat milk powder',
 'goji berries',
 'grains',
 'granola',
 'grape leaves',
 'grapefruit',
 'grapes',
 'gravy',
 'green apples',
 'green beans',
 'green bell pepper',
 'green cake',
 'green chili',
 'green chilies',
 'green grapes',
 'green onion',
 'green onions',
 'green peas',
 'green pepper',
 'green peppers',
 'green tea',
 'green tea ice cream',
 'green vegetables',
 'green_onion',
 'green_onions',
 'green_pepper',
 'green_peppers',
 'greens',
 'grilled chicken',
 'grilled eel',
 'grilled fish',
 'grilled lemon',
 'grilled meat',
 'grilled squash',
 'grilled_meat',
 'ground beef',
 'ground meat',
 'ground pork',
 'ground_meat',
 'gummy bears',
 'ham',
 'hamburger patty',
 'hamburger_steak',
 'hash browns',
 'hawthorn',
 'herbs',
 'honey',
 'honeycomb',
 'hot dog',
 'hot dogs',
 'hot pot',
 'hot pot ingredients',
 'hummus',
 'ice',
 'ice cream',
 'ice cream bar',
 'insects',
 'jackfruit',
 'jelly',
 'juice',
 'jujube',
 'jujubes',
 'kale',
 'kataifi',
 'kebab',
 'kebabs',
 'kefir',
 'ketchup',
 'kibble',
 'kimchi',
 'kiwi',
 'kiwifruit',
 'kozinaki',
 'lamb',
 'lamb_chops',
 'lasagna',
 'leaf',
 'leafy greens',
 'leaves',
 'leeks',
 'legumes',
 'lemon',
 'lemons',
 'lentil curry',
 'lentils',
 'lettuce',
 'lime',
 'liver',
 'lobster',
 'lollipops',
 'longan',
 'loquat',
 'lotus root',
 'lotus root slices',
 'lotus_root',
 'lychee',
 'macaron',
 'mackerel',
 'madeleines',
 'main dish',
 'main ingredient',
 'main_dish',
 'mango',
 'mangosteen',
 'marshmallows',
 'mashed potatoes',
 'matcha',
 'matcha cream',
 'mayonnaise',
 'mcspicy wings',
 'meat',
 'meat dish',
 'meat filling',
 'meat patty',
 'meat sauce',
 'meat skewers',
 'meat topping',
 'meatball',
 'meatballs',
 'meatloaf',
 'melon',
 'melon seeds',
 'meringue',
 'milk',
 'milk tea',
 'minced meat',
 'mini cakes',
 'mint',
 'mint candy',
 'mint ice cream',
 'mix',
 'mixed dish',
 'mixed fruits',
 'mixed vegetables',
 'mochi',
 'momos',
 'morning glory',
 'mozzarella',
 'mozzarella_sticks',
 'muffin',
 'mulberries',
 'mung beans',
 'mushrooms',
 'mussels',
 'mustard',
 'naan',
 'nabati',
 'nachos',
 'nectarine',
 'nextar',
 'noodle dish',
 'noodle soup',
 'noodles',
 'nori',
 'nougat',
 'nuts',
 'oat milk',
 'oat snack',
 'oatmeal',
 'oats',
 'octopus',
 'oil',
 'okra',
 'olive oil',
 'olives',
 'omelet',
 'onion',
 'onion rings',
 'onion_rings',
 'onions',
 'orange',
 'orange juice',
 'orange pepper',
 'oranges',
 'oreo',
 'organ meat',
 'other dishes',
 'other ingredients',
 'other vegetables',
 'other_dishes',
 'oysters',
 'pakoras',
 'pancake',
 'pancakes',
 'panna cotta',
 'papaya',
 'parsley',
 'passion fruit',
 'pasta',
 'pasta shells',
 'pastries',
 'pastry',
 'pastry crust',
 'pastry1',
 'pastry2',
 'pastry3',
 'pastry4',
 'patties',
 'patty',
 'peach',
 'peach slices',
 'peaches',
 'peanut butter',
 'peanut sauce',
 'peanuts',
 'pear',
 'pears',
 'peas',
 'pecans',
 'pepper',
 'peppers',
 'pesto',
 'pickled fish',
 'pickled radish',
 'pickled vegetables',
 'pickles',
 'pie',
 'pine nuts',
 'pineapple',
 'pistachio tart',
 'pistachios',
 'pizza',
 'pizza slice',
 'pizza_slice',
 'plantain',
 'plantain chips',
 'plantains',
 'plum',
 'plums',
 'poached egg',
 'pomegranate',
 'pomelo',
 'popcorn',
 'popsicle',
 'pork',
 'pork belly',
 'pork bits',
 'pork brain',
 'pork bun',
 'pork hock',
 'pork hocks',
 'pork knuckle',
 'pork ribs',
 'pork trotters',
 'pork_belly',
 'pork_floss',
 'pork_head',
 'porridge',
 'potato',
 'potato chips',
 'potato sticks',
 'potato wedge',
 'potatoes',
 'pounded yam',
 'powder',
 'preserved egg',
 'processed meat',
 'protein',
 'protein drink',
 'protein_source',
 'pudding',
 'puff pastry',
 'pumpkin',
 'pumpkin seeds',
 'puri',
 'purple yam',
 'quinoa',
 'radish',
 'radishes',
 'raisins',
 'rambutan',
 'rasgulla',
 'raspberries',
 'raspberry',
 'raw vegetables',
 'red apples',
 'red bean paste',
 'red beans',
 'red bell pepper',
 'red chili',
 'red chilies',
 'red currants',
 'red grapes',
 'red pepper',
 'red peppers',
 'ribs',
 'rice',
 'rice cake',
 'rice cakes',
 'rice flour',
 'rice noodles',
 'rice paper',
 'rice porridge',
 'rice rolls',
 'ricotta',
 'roast meat',
 'roasted chicken',
 'roasted duck',
 'roasted meat',
 'roasted potatoes',
 'roll',
 'rolled meat',
 'rolls',
 'root_vegetables',
 'roti',
 'rye bread',
 'sago',
 'salad',
 'salad greens',
 'salmon',
 'salmon_sushi',
 'salsa',
 'sambal',
 'samosa',
 'samosas',
 'sandwich',
 'sashimi',
 'sauce',
 'sauces',
 'sauerkraut',
 'sausage',
 'sausages',
 'savory pancake',
 'savory snack',
 'scallions',
 'scallop',
 'scallops',
 'scrambled eggs',
 'sea urchin',
 'seafood',
 'seafood skewers',
 'seafood stew',
 'seafood topping',
 'seasoning',
 'seaweed',
 'seeds',
 'semolina',
 'sesame',
 'sesame bread',
 'sesame seeds',
 'shaved ice',
 'shellfish',
 'short ribs',
 'shortbread',
 'shredded crab',
 'shredded meat',
 'shredded vegetables',
 'shrimp',
 'shrimp dish',
 'shrimp porridge',
 'shrimp_dumpling',
 'side',
 'side dish',
 'side dishes',
 'side salad',
 'side vegetables',
 'side_dish',
 'side_dishes',
 'side_item',
 'sides',
 'skewered meat',
 'skewers',
 'skittles',
 'sliced meat',
 'small fish',
 'smoked salmon',
 'smoothie',
 'snack',
 'snack balls',
 'snack mix',
 'snack sticks',
 'snack1',
 'snack2',
 'snack3',
 'snack_mix',
 'snack_sticks',
 'snacks',
 'snails',
 'snap peas',
 'soba noodles',
 'soda',
 'soup',
 'soup base',
 'sour cream',
 'soy milk',
 'soy sauce',
 'soybeans',
 'soymilk',
 'spaghetti',
 'spice mix',
 'spices',
 'spinach',
 'split peas',
 'sponge cake',
 'spread',
 'spring roll',
 'spring rolls',
 'spring_rolls',
 'sprouts',
 'squash',
 'squid',
 'starch',
 'starchy side',
 'starfruit',
 'steak',
 'steamed vegetables',
 'steamed_buns',
 'stew',
 'sticks',
 'sticky rice',
 'stir-fried chicken',
 'stir-fried vegetables',
 'stir-fried vegetables and meat',
 'stir-fry',
 'strawberries',
 'strawberry',
 'stuffing',
 'sugar',
 'sugar_syrup',
 'sun-dried tomatoes',
 'sunflower seeds',
 'sushi',
 'sushi rice',
 'sushi_roll',
 'sweet bread',
 'sweet dish',
 'sweet paste',
 'sweet potato',
 'sweet potatoes',
 'sweet soup',
 'sweet toppings',
 'sweet treat',
 'sweetener',
 'swiss roll',
 'syrup',
 'tacos',
 'tangerine',
 'tapioca',
 'tapioca balls',
 'tapioca pearls',
 'taro cake',
 'tart',
 'tart base',
 'tart crust',
 'tea',
 'tea bag',
 'tea leaves',
 'tea_bag',
 'tempeh',
 'tempura',
 'toast',
 'tofu',
 'tomato',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'topping',
 'toppings',
 'tortilla',
 'tortilla chips',
 'tortillas',
 'tuna',
 'tuna_sushi',
 'turkey',
 'twix',
 'udon',
 'vegetable bites',
 'vegetable curry',
 'vegetable dish',
 'vegetable mixture',
 'vegetable pancake',
 'vegetable sauce',
 'vegetable skewers',
 'vegetable stew',
 'vegetable stir-fry',
 'vegetables',
 'wafer',
 'wafer cone',
 'wafer sticks',
 'waffle',
 'waffles',
 'walnut',
 'walnut milk',
 'wasabi',
 'water',
 'watermelon',
 'watermelon candy',
 'whipped cream',
 'whole grain bread',
 'wontons',
 'wood ear mushrooms',
 'wrap',
 'wrapper',
 'yakult',
 'yams',
 'yeast',
 'yellow cherries',
 'yogurt',
 'zucchini'}

In [ ]:
num_ingredients = len(ingredients)
initial_vals = [0] * num_ingredients
ingredients_df = {'ingredients': list(ingredients), 'iron': initial_vals, 'calcium': initial_vals, 'vitamin_c': initial_vals}
ingredients_df = pd.DataFrame(ingredients_df)
ingredients_df

         ingredients  iron  calcium  vitamin_c
0         tuna_sushi     0        0          0
1          cucumbers     0        0          0
2              kebab     0        0          0
3                bun     0        0          0
4       energy drink     0        0          0
..               ...   ...      ...        ...
817            beets     0        0          0
818            juice     0        0          0
819           muffin     0        0          0
820  main ingredient     0        0          0
821    bamboo shoots     0        0          0

[822 rows x 4 columns]

In [66]:
# Load and get api key from .env
load_dotenv()
api_key = os.getenv("API_KEY")

In [89]:
FOODS_SEARCH_URL = 'https://api.nal.usda.gov/fdc/v1/foods/search'
FOODS_DETAIL_URL = 'https://api.nal.usda.gov/fdc/v1/food/'

nutrition_data = {}
ingredients_test = ['abalone', 'chicken', 'tuna']

In [121]:
# Search for food
ingredient = 'chicken'
food_query = ingredient
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')
data = r.json()
data_df = pd.DataFrame.from_dict(data['foods'])
if len(data_df) == 0:  # Data not found
    r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}')
    data = r.json()
    data_df = pd.DataFrame.from_dict(data['foods'])
data_df

,fdcId,description,commonNames,additionalDescriptions,dataType,ndbNumber,publishedDate,foodCategory,mostRecentAcquisitionDate,allHighlightFields,score,microbes,foodNutrients,finalFoodInputFoods,foodMeasures,foodAttributes,foodAttributeTypes,foodVersionIds
0,2514746,"Chicken, ground, with additives, raw",,,Foundation,5332,2023-04-20,Poultry Products,2023-01-09,,201.99571,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
1,2646170,"Chicken, breast, boneless, skinless, raw",,,Foundation,100304,2023-10-26,Poultry Products,2023-04-03,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
2,2727569,"Chicken, breast, meat and skin, raw",,,Foundation,100375,2025-04-24,Poultry Products,2024-10-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
3,2727566,"Chicken, drumstick, meat and skin, raw",,,Foundation,100372,2025-04-24,Poultry Products,2024-10-13,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
4,2646171,"Chicken, thigh, boneless, skinless, raw",,,Foundation,100305,2023-10-26,Poultry Products,2023-03-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
5,2727567,"Chicken, thigh, meat and skin, raw",,,Foundation,100373,2025-04-24,Poultry Products,2024-10-20,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
6,2727568,"Chicken, wing, meat and skin, raw",,,Foundation,100374,2025-04-24,Poultry Products,2024-10-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
7,331897,"Chicken, broilers or fryers, drumstick, meat o...",,,Foundation,5671,2019-04-01,Poultry Products,2010-05-11,,153.41048,[],"[{'nutrientId': 1253, 'nutrientName': 'Cholest...",[],[],[],[],[]
8,331960,"Chicken, broiler or fryers, breast, skinless, ...",,,Foundation,5746,2019-04-01,Poultry Products,2012-11-12,,136.97621,[],"[{'nutrientId': 1170, 'nutrientName': 'Pantoth...",[],[],[],[],[]

In [122]:
nutrients = pd.DataFrame(data_df.iloc[0]['foodNutrients'])
nutrients = nutrients.loc[nutrients['nutrientId'].isin([1087, 1089, 1162])][['nutrientName', 'value', 'unitName']]
nutrients

   nutrientName  value unitName
0      Iron, Fe  0.593       MG
13  Calcium, Ca  5.820       MG

In [116]:
# Get food nutrients
if len(data_df) > 0:  # Data found
    nutrients = pd.DataFrame(data_df.iloc[0]['foodNutrients'])
    nutrients = nutrients.loc[nutrients['nutrientId'].isin([1087, 1089, 1162])]
    nutrition_data[ingredient] = {'found': True, 'vitamin_c': 0, 'iron': 0, 'calcium': 0}
else:  # Data not found
    nutrition_data[ingredient] = {'found': False, 'vitamin_c': 0, 'iron': 0, 'calcium': 0}

In [117]:
nutrients

,nutrientId,nutrientName,nutrientNumber,unitName,value,rank,indentLevel,foodNutrientId
10,1087,"Calcium, Ca",301,MG,39.00,5300,1,34198114
11,1089,"Iron, Fe",303,MG,3.97,5400,1,34198115
28,1162,"Vitamin C, total ascorbic acid",401,MG,2.00,6300,1,34198132