# Get Bioavailable Iron from USDA

In [12]:
# Parameters
SAVE_DFS = False

In [13]:
import os
import pandas as pd
import requests

from IPython.display import Image
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [15]:
# Load splits from CSVs
df_train = pd.read_csv('../data/train/df_train.csv')
df_val = pd.read_csv('../data/val/df_val.csv')
df_test = pd.read_csv('../data/test/df_test.csv')

df_train.head(2)

,image_url,camera_or_phone_prob,food_prob,dish_name,food_type,ingredients,portion_size,nutritional_profile,cooking_method,sub_dt,image_name
0,https://file.b18a.io/7832973280900104501_54585...,0.8,0.90,oysters,homemade food,['oysters'],{'oysters': '500g'},"{'fat_g': 5.0, 'protein_g': 20.0, 'calories_kc...",raw,20250710,7832973280900104501_545859_.jpeg
1,https://file.b18a.io/7835136777400102715_70587...,0.7,0.95,grilled steak,restaurant food,"['steak', 'broccoli', 'potato', 'tomato', 'sau...","{'steak': '250g', 'broccoli': '50g', 'potato':...","{'fat_g': 30.0, 'protein_g': 50.0, 'calories_k...",grilling,20250702,7835136777400102715_705873_.jpeg

In [31]:
# Combine dfs
df_all = pd.concat([df_train, df_val, df_test])
df_all = df_all.reset_index()

df_all.shape

(5000, 12)

In [37]:
df_all['portion_size'][0]

"{'oysters': '500g'}"

In [28]:
# Get all ingredients
ingredients = set()
for row in df_all.itertuples():
    ingredients.update(row.portion_size.keys())
print(f'{len(ingredients)=}')
ingredients

AttributeError: 'str' object has no attribute 'keys'

In [18]:
# Load and get api key from .env
api_key = os.getenv("API_KEY")

In [23]:
food_query = 'chicken'
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')

In [24]:
data = r.json()
data_df = pd.DataFrame.from_dict(data['foods'])
data_df

,fdcId,description,commonNames,additionalDescriptions,dataType,ndbNumber,publishedDate,foodCategory,mostRecentAcquisitionDate,allHighlightFields,score,microbes,foodNutrients,finalFoodInputFoods,foodMeasures,foodAttributes,foodAttributeTypes,foodVersionIds
0,2514746,"Chicken, ground, with additives, raw",,,Foundation,5332,2023-04-20,Poultry Products,2023-01-09,,201.99571,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
1,2646170,"Chicken, breast, boneless, skinless, raw",,,Foundation,100304,2023-10-26,Poultry Products,2023-04-03,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
2,2727569,"Chicken, breast, meat and skin, raw",,,Foundation,100375,2025-04-24,Poultry Products,2024-10-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
3,2727566,"Chicken, drumstick, meat and skin, raw",,,Foundation,100372,2025-04-24,Poultry Products,2024-10-13,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
4,2646171,"Chicken, thigh, boneless, skinless, raw",,,Foundation,100305,2023-10-26,Poultry Products,2023-03-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
5,2727567,"Chicken, thigh, meat and skin, raw",,,Foundation,100373,2025-04-24,Poultry Products,2024-10-20,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
6,2727568,"Chicken, wing, meat and skin, raw",,,Foundation,100374,2025-04-24,Poultry Products,2024-10-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
7,331897,"Chicken, broilers or fryers, drumstick, meat o...",,,Foundation,5671,2019-04-01,Poultry Products,2010-05-11,,153.41048,[],"[{'nutrientId': 1253, 'nutrientName': 'Cholest...",[],[],[],[],[]
8,331960,"Chicken, broiler or fryers, breast, skinless, ...",,,Foundation,5746,2019-04-01,Poultry Products,2012-11-12,,136.97621,[],"[{'nutrientId': 1170, 'nutrientName': 'Pantoth...",[],[],[],[],[]